// AUTO-GENERATED by scripts/extract-nsw-reference-data.ts
// Source: vendor/wildlife-rehabilitation-detailed-report-2025-26.xlsx
// Do not edit by hand. Re-run the extractor when NSW publishes a new template.
//
// NSW DCCEEW controlled vocabularies used on the Detailed Report's Datasheet
// tab. Values match the official drop-down text exactly so they can be
// emitted into exports without translation.

export interface NswPicklistItem {
  value: string;
  definition?: string;
  example?: string;
}

export const NSW_SEX: readonly string[] = [
  "Female",
  "Male",
  "Hermaphrodite",
  "Unknown"
] as const;

export const NSW_LIFE_STAGE: readonly string[] = [
  "Adult",
  "Young",
  "Egg",
  "Unknown"
] as const;

export const NSW_POUCH_CONDITION: readonly string[] = [
  "Lactating",
  "Non-Lactating",
  "Pinkie Attached",
  "Pouch Young",
  "Back Young",
  "N/A"
] as const;

export const NSW_ANIMAL_CONDITION: NswPicklistItem[] = [
  { value: "Abnormal behaviour", definition: "Animal is displaying behaviours that are not typical of its species or that do not seem quite right in the situation", example: "Kangaroo not moving away when approached by humans; koala that has been sitting on the ground for a few days" },
  { value: "Burnt", definition: "Animal is wounded, altered or impacted by fire or heat", example: "Burnt paws, fur, skin as a result of bushfire, hot pavement or other surfaces; burnt from a barbeque" },
  { value: "Cold stress / Hypothermia", definition: "Abnormally low body temperature", example: "Symptoms include shivering, fatigue, lack of mental awareness, shallow and/or slow breathing" },
  { value: "Concussed", definition: "Animal appears to be suffering from an impact causing temporary unconsciousness or confusion", example: "Bird has flown into a window" },
  { value: "Dehydrated", definition: "Excess loss of body water", example: "Any animal suffering symptoms of dehydration which include sunken eyes, skin tenting, lethargy, dry mouth, cold extremities" },
  { value: "Difficulty breathing", definition: "Animal is demonstrating trouble breathing", example: "Heaving; rapid inhalation" },
  { value: "Diseased", definition: "Animal that is suffering from disease, either internal or external", example: "Beak and feather; lyssavirus; mange; chlamydia; chytrid" },
  { value: "Exhausted", definition: "Complete lack of energy", example: "Wedge-tailed shearwaters that have flown off their migratory flightpath and cannot resume flight due to exhaustion" },
  { value: "Eye injury", definition: "Animal has suffered injury to the eye", example: "Animal with infected eye; cataracts; animal with damaged eye" },
  { value: "Feather/fur damage", definition: "Animal has damage to or a lack of feathers or fur", example: "Missing tail feathers; damaged wing feathers" },
  { value: "Float", definition: "The accumulation of gas in the body cavity and gut of a sea turtle, making it incapable of diving", example: "Buoyant sea turtle" },
  { value: "Geriatric", definition: "The only condition obviously affecting the animal is that it is old", example: "Koala with significant tooth wear as a result of age, causing it to starve" },
  { value: "Heat stress / Hyperthermia", definition: "Too much heat is absorbed by the animal, causing stress. Animal has overheated", example: "Flying-fox in extreme temperatures; symptoms include open mouth breathing (gaping), panting, licking of forearms" },
  { value: "Humanised", definition: "Animal has been cared for by a member of the public for a prolonged period of time and is displaying abnormal behaviour or dependence toward humans", example: "Joey kangaroo seeking out the attention of people" },
  { value: "Infection", definition: "Includes infection both in and/or outside of the body", example: "An injury or wound has become infected" },
  { value: "Injury to beak/mouth", definition: "Animal has sustained physical trauma to the beak or mouth", example: "Cracked beak; hard palate fracture" },
  { value: "Injury to body", definition: "Animal has sustained physical trauma to the body, not limbs, tail or head/face", example: "Puncture wounds to the body" },
  { value: "Injury to fin", definition: "Animal has sustained physical trauma to the fin", example: "Turtle has been hit by a propeller causing lacerations to the fin" },
  { value: "Injury to forelimb/wing", definition: "Animal has sustained physical trauma to the forelimb/wing", example: "Fracture or broken bone in the wing" },
  { value: "Injury to head", definition: "Animal has sustained physical trauma to the head", example: "Pecking wound on head" },
  { value: "Injury to hindlimb", definition: "Animal has sustained physical trauma to the hindlimb", example: "Hip fracture or broken tibia" },
  { value: "Injury to patagium", definition: "A glider or bat has sustained injury to its patagium, i.e. the membrane between the forelimbs and hindlimbs that enables flight/gliding", example: "Glider that has a tear in its patagium" },
  { value: "Injury to tail", definition: "Animal has sustained physical trauma to the tail", example: "Missing part of tail; wound to tail" },
  { value: "Internal injury", definition: "Animal has sustained internal trauma", example: "Internal bleeding; puncture of air sacs; ruptured spleen" },
  { value: "Malnourished", definition: "Animal is suffering from a lack of quality food", example: "Animal is underweight/emaciated" },
  { value: "Moribund", definition: "Animal appears non-responsive, is near death or in the process of dying", example: "Koala that is so ill, old or impacted by disease that it is close to death" },
  { value: "Multiple health issues", definition: "Animal is suffering from a number of health issues and its condition cannot be attributed to a single one", example: "Geriatric koala that is suffering from chlamydia and has multiple injuries from being hit by a car" },
  { value: "Myopathy", definition: "A non-infection condition in which muscle damage results from extreme exertion, stress or struggle", example: "Kangaroo that has been chased by a dog; flying-fox that has been struggling for a prolonged period of time" },
  { value: "Neurological damage", definition: "Damage to the brain, spine and nerves", example: "‘Stargazing’ in reptiles; loss of sensation; seizures; head tilting; blindness; muscle weakness; confusion" },
  { value: "No apparent distress", definition: "Animal appears stable and there is no discernible disorder", example: "Animal that has no health concerns and is being relocated; an animal that appears to be healthy with no obvious signs of ailment" },
  { value: "No apparent injury", definition: "Animal is uninjured", example: "Waterbird that is entangled in netting but has not sustained any injury" },
  { value: "Orphaned", definition: "Mother of the animal is known to be deceased", example: "Joey in the pouch of its deceased mother" },
  { value: "Paralysis", definition: "Loss of the ability to move limbs", example: "Animal is unable to move back legs" },
  { value: "Parasite burden", definition: "An animal that is suffering from a higher than average parasite load", example: "Eastern blue-tongued lizard thats body is covered in ticks" },
  { value: "Shell injury", definition: "Turtle has sustained injury to any part of its shell", example: "Eastern snake-necked turtle that has a fractured shell" },
  { value: "Shock", definition: "A critical condition caused by a sudden decrease in blood flow resulting in poor oxygen delivery to the body", example: "Pale gums, respiratory failure, hyperventilation, rapid and faint heartbeat, cold to touch" },
  { value: "Skin problem", definition: "Animal is suffering from a skin condition requiring treatment", example: "Dermatitis" },
  { value: "Tumour", definition: "Swelling of an area of the body caused by abnormal overgrowth of tissue", example: "Skin cancer in an animal; facial tumours" },
  { value: "Waterlogged", definition: "Saturated or full of water", example: "An animal rescued from a pool" },
  { value: "Unknown", definition: "The condition of the animal is not known and could not be determined during its time in care", example: "Animal is not healthy but the condition cannot be determined" },
];

export const NSW_ENCOUNTER_TYPE: NswPicklistItem[] = [
  { value: "Abandoned/Orphaned", definition: "An animal’s parent is known to be deceased or it is found on its own with no sign of its parents or family group.", example: "Joey removed from the pouch of its deceased mother; possum ejects joey from its pouch in time of stress; a dependent young is found and the parent’s condition and location is unknown; a chick cannot be reunited with its parents because the nest is too high and so needs to come into care" },
  { value: "Attack - Bird", definition: "Animal has been attacked by a bird", example: "Crested pigeon that has been attacked by noisy miners" },
  { value: "Attack - Cat", definition: "Animal has been attacked by a cat", example: "Ringtail possum that has been brought in by the cat" },
  { value: "Attack - Dog", definition: "Animal has been attacked by a dog", example: "Brushtail possum that has been bitten by a dog" },
  { value: "Attack - Fox", definition: "Animal has been attacked by a fox", example: "Duck that has been attacked by a fox" },
  { value: "Attack - Same species", definition: "Animal has been attacked by a conspecific (i.e. member of its own species)", example: "Noisy miner that has been attacked by other noisy minors" },
  { value: "Attack - Suspected/Other", definition: "Animal has sustained injuries or is behaving in a way that suggests it has been attacked by something", example: "This should be used when the source of the attack is unknown; human attack should not be categorised here but in the ‘Intentional harm’ encounter type" },
  { value: "Collision - Building", definition: "Animal has had an impact with a building including windows", example: "Bird that has flown into a window" },
  { value: "Collision - Motor vehicle", definition: "Animal has had an impact with a car", example: "Macropod hit by a car; tawny frogmouth hit by a car" },
  { value: "Collision - Other", definition: "Animal has had an impact with something, whether a natural or manmade structure", example: "Bird that has flown into a glass pool fence" },
  { value: "Collision - Vessel strike", definition: "Animal has had an impact with a boat", example: "Seabird that has collided with a boat" },
  { value: "Dependent on parent taken into care", definition: "A dependent young has been brought into care as a result of its parent requiring treatment", example: "A dependent koala joey is not ill or injured but is being kept with its mother to be raised and fed while the mother undergoes rehabilitation" },
  { value: "Disease - Botulism", definition: "Animal is confirmed either visually or through vet assessment to be suffering from botulism", example: "Botulism is a disease common in waterbirds that causes paralysis" },
  { value: "Disease - Chlamydia", definition: "Animal is confirmed either visually or through vet assessment to have chlamydia", example: "Ocular and urogenital chlamydia in koalas; chlamydia in birds" },
  { value: "Disease - External parasite", definition: "Animal has parasites on its body", example: "Paralysis tick; lice; maggots; flat flies" },
  { value: "Disease - Internal parasite", definition: "Animal has visible internal parasites or confirmed symptoms associated with internal parasites", example: "Examples of internal parasites include gapeworm, tapeworm, throat worm" },
  { value: "Disease - Mange", definition: "Animal has mange (i.e. scabies mites) regardless of what stage", example: "Wombats or other mammals with mange" },
  { value: "Disease - Other", definition: "Animal is affected with any other disease not listed as a category", example: "Exudative dermatitis in possums" },
  { value: "Disease - PBFD", definition: "Birds suffering from psittacine circoviral disease, aka beak and feather, beak and feather disease virus, PCD and runners", example: "Runners in lorikeets; beak and feather in sulphur crested cockatoos; PCD in birds of prey" },
  { value: "Domestic Pet - Escaped", definition: "Animal is found and determined through species or behavioural characteristics to be a lost or escaped domestic pet", example: "This is typically a bird or reptile. Common escaped pets include cockatiels, sulphur-crested cockatoos, rainbow lorikeets, bearded dragons and pythons" },
  { value: "Domestic Pet - Seized", definition: "Pet has come into care as a result of an authorised seizure of animals", example: "An animal has been obtained as a result of a police/government seizure and is being held until court proceedings have been finalised" },
  { value: "Domestic Pet - Surrendered", definition: "Pet animal has been handed over to the organisation", example: "Owner can no longer look after their pet lizard or bird and is giving it to the organisation for rehoming" },
  { value: "Electrocution", definition: "Animal is injured or killed via an electric shock", example: "Flying-fox on powerlines; possum that has been electrocuted on wire" },
  { value: "Entanglement - Marine debris", definition: "Animal is impacted by any manmade material in and around waterways including fishing gear and litter, in a manner from which it cannot free itself", example: "Pelican with fishing hook embedded in its chest; seal entangled in fishing line" },
  { value: "Entanglement - Netting", definition: "Animal is impacted by netting (other than marine) in a manner from which it cannot free itself", example: "Snake or flying-fox caught in fruit tree netting" },
  { value: "Entanglement - Other", definition: "Animal is impacted by any material or object without a standalone category in a manner from which it cannot free itself", example: "Animal is entangled in rope, shoelace, plastic rings" },
  { value: "Entanglement - Wire", definition: "Animal is impacted by barbed wire in a manner from which it cannot free itself", example: "Flying-fox entangled in barbed wire fencing; ‘fence-hanger’ in kangaroos; glider entangled in barbed wire fencing" },
  { value: "Entrapment", definition: "Animal is stuck in such a manner that it cannot free itself", example: "Animal has fallen into a storm drain and cannot free itself; possum stuck in a chimney; bird stuck in roof or wall cavity; kangaroo with bin lid stuck over its head" },
  { value: "Event - Drought", definition: "Animal is suffering from the impacts of drought, i.e. prolonged period of low rainfall leading to a lack of water", example: "Malnourished or dehydrated macropods in drought affected area" },
  { value: "Event - Extreme heat", definition: "Animal is suffering from the impacts of prolonged periods of abnormally high temperatures", example: "Flying-fox heat stress events" },
  { value: "Event - Fire", definition: "Animal is suffering from the impacts of fire either natural or manmade", example: "Bushfire burn victims" },
  { value: "Event - Flood", definition: "Animal is suffering from the impacts of flood", example: "Animal water-logged in flood event" },
  { value: "Event - Storm", definition: "Animal is suffering from the impacts of a storm", example: "Bird has been blown out of nest or off migratory course due to storm event" },
  { value: "Fallen from nest or tree", definition: "Animal has fallen from a nest or tree and the cause cannot be attributed to any other encounter type", example: "Nestling bird fallen from nest in high winds; nestling bird failed attempt at fledging; possum fallen from a tree" },
  { value: "Fouled by substance", definition: "Animal is partially or wholly covered by a substance", example: "Animal in an oil spill or stuck to an insect sticky trap" },
  { value: "Human Impact - Habitat alteration / Tree felling", definition: "Animal is displaced or otherwise affected by localised alteration of their habitat or immediate environment", example: "This is not habitat loss on a mass scale. This is referring to animals that have been immediately displaced or needing relocation due to local development or a tree being chopped down" },
  { value: "Human impact - Intentional harm", definition: "Animal has been injured by purposeful human action", example: "Acts of cruelty; shooting; physical violence; illegal trapping" },
  { value: "Human Impact - Interference", definition: "Animal has been interfered with by a member of the public, regardless of their intent", example: "Fledgling birds in spring; people keeping orphaned joeys and calling days/weeks later" },
  { value: "Ingestion of a foreign object", definition: "Animal has taken into its body via the mouth an object that it would not normally or should not normally ingest", example: "Snake swallowing golf ball or artificial eggs; seagull that has ingested a fishing hook" },
  { value: "Poisoned", definition: "Animal has ingested a poisonous substance either directly or indirectly", example: "Possum that has eaten snail or rat bait; bird of prey that has eaten a rodent affected by bait" },
  { value: "Negative interaction", definition: "A person has reported a negative interaction with an animal and requested action", example: "Ducklings in a backyard pool; snake under a fridge; possum in the house" },
  { value: "Stranded / Haul out", definition: "Whale, dolphin or turtle has been found on the land and cannot return itself to the water, or seal or penguin has temporarily left the water and is found on land", example: "Examples included in the definition" },
  { value: "Unsuitable environment", definition: "An animal is located in an environment that poses a risk to itself or that it would not typically be found in", example: "Echidna crossing a road" },
  { value: "Unknown", definition: "The reason for the animal coming into care cannot be determined and is therefore not known" },
];

export const NSW_FATE: NswPicklistItem[] = [
  { value: "Advice provided", definition: "The situation was handled by providing advice to an enquiry", example: "Member of the public enquires about possums in the roof, nesting brush turkeys, etc. and is provided with advice only" },
  { value: "Could not locate for rescue", definition: "Animal is unable to be located for rescue", example: "Called out to rescue a bird on the ground and when the rescuer arrives they cannot find it; member of the public calls to tell you that the animal has disappeared" },
  { value: "Dead prior to rescuer arriving", definition: "Animal has died between the time the call was logged and a rescuer arrived, or is an animal that is deceased and requires pouch checking", example: "When the rescuer arrives at the rescue location they determine the animal has already died; a member of the public rings back after logging an incident to report the animal has died" },
  { value: "Died in care", definition: "Animal has died any time between the initial rescue and before being released", example: "Animal died after being rescued" },
  { value: "Escaped from care", definition: "Animal has freed itself from its care facilities and cannot be located", example: "Possum escapes from its enclosure and cannot be found" },
  { value: "Euthanased by rehabilitation group", definition: "Confirmed euthanasia by the rehabilitation group based on approved methods as outlined in the species’ relevant code of practice", example: "Animal has been euthanased by a member of a group in accordance with approved methods as outlined in the code of practice; approved member that holds the required firearms licence euthanasing a kangaroo using a firearm" },
  { value: "Euthanased by vet", definition: "Confirmed euthanasia of the animal by a veterinarian", example: "Animal has been euthanased by a qualified veterinarian" },
  { value: "Euthanased by police", definition: "Animal has been euthanased using a firearm by a police officer", example: "Police are called out to euthanase a kangaroo on the side of the road" },
  { value: "Euthanased by other", definition: "An animal has been euthanased by an approved person not listed as a standalone category", example: "Kangaroo euthanased using a firearm by an NPWS ranger or RSPCA officer" },
  { value: "Evaded capture", definition: "Attempt(s) to capture the animal were not successful", example: "Animal was not able to be captured during rescue, e.g. a bird that flew away during rescue" },
  { value: "In care", definition: "An animal is still undergoing rehabilitation at the time of reporting", example: "Any animal that is still in care at the time of reporting" },
  { value: "Left and observed", definition: "Animal required no immediate intervention and was therefore left in the same condition it was found", example: "Checking on a fledgling chick; a member of the public has been asked to keep an eye on an animal and report back if anything changes" },
  { value: "Permanent care - Companion (approved)", definition: "Animal has been approved by NPWS to be held as a permanent care animal for the purposes of being a companion to other animals coming into care", example: "Animal belonging to a social species endemic to area of operation" },
  { value: "Permanent care - External/Community education (approved)", definition: "Animal has been approved by NPWS to be held as a permanent care animal for education purposes within the community. This requires Exhibited Animals Act approval." },
  { value: "Permanent care - Internal training (approved)", definition: "Animal has been approved by NPWS to be held as a permanent care animal for education purposes within the rehabilitation organisation. This requires ethics approval." },
  { value: "Permanent care - Research (approved)", definition: "Animal has been approved by NPWS to be held as a permanent care animal as part of an authorised research project" },
  { value: "Rehomed", definition: "A seized, surrendered or domestic pet (when the owner cannot be located) is rehomed with a licensed native animal keeper, as per NPWS policy", example: "Children’s python has been rehomed with a person licensed to keep this species" },
  { value: "Released", definition: "An animal that has been rehabilitated and returned to the wild", example: "Releasing any animal" },
  { value: "Relocated", definition: "A healthy and/or uninjured animal was moved from one location to another, without it requiring care", example: "Relocating a snake from inside a house to appropriate habitat" },
  { value: "Resolved by vets", definition: "When the animal was last known to be at the vet but the exact fate is not known", example: "Animal recorded in the system as being at the vet but the vet does not know the fate of the animal" },
  { value: "Returned to owner", definition: "A domestic pet has been reunited with its owner", example: "Owner of a pet sulphur-crested cockatoo has been located and their bird returned to them" },
  { value: "Reunited with parents", definition: "A young animal has been confirmed as returned and accepted by its parents", example: "Nestling chick has fallen from the nest and has been placed back in the nest by a rescuer. The reuniting attempt was successful and the parent birds are confirmed to be attending to the chick" },
  { value: "Transferred to an authorised fauna park / zoo", definition: "An animal has been transferred to a fauna park or zoo for treatment or permanent care after obtaining approval from the relevant person(s) within an organisation", example: "Non-releasable koala has been approved for permanent care at a fauna park" },
  { value: "Transferred to other wildlife rehabilitation organisation", definition: "Animal has been physically transferred from the care of one wildlife rehabilitation organisation to another", example: "Animal and its care records (e.g. condition, weights, treatments, unique identifying number) are given to another group for continued care of the animal. This could be for specialist care, facilities required or capacity of group" },
];

function normalise(value: string | null | undefined): string {
  return (value ?? '').trim().toLowerCase();
}

function isInPicklist(list: readonly string[] | readonly NswPicklistItem[], value: string | null | undefined): boolean {
  const n = normalise(value);
  if (!n) return false;
  return list.some((item: string | NswPicklistItem) => {
    const v = typeof item === 'string' ? item : item.value;
    return normalise(v) === n;
  });
}

export const isKnownNswSex = (v: string | null | undefined) => isInPicklist(NSW_SEX, v);
export const isKnownNswLifeStage = (v: string | null | undefined) => isInPicklist(NSW_LIFE_STAGE, v);
export const isKnownNswPouchCondition = (v: string | null | undefined) => isInPicklist(NSW_POUCH_CONDITION, v);
export const isKnownNswAnimalCondition = (v: string | null | undefined) => isInPicklist(NSW_ANIMAL_CONDITION, v);
export const isKnownNswEncounterType = (v: string | null | undefined) => isInPicklist(NSW_ENCOUNTER_TYPE, v);
export const isKnownNswFate = (v: string | null | undefined) => isInPicklist(NSW_FATE, v);
