-- Seed growth reference data
INSERT INTO species_growth_references (
  id, species_name, sex, age_days, weight_grams,
  head_length_mm, ear_length_mm, arm_length_mm, leg_length_mm,
  foot_length_mm, tail_length_mm, body_length_mm, wing_length_mm,
  reference
) VALUES
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 0, 1, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 20, 10, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 40, 22, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 60, 40, NULL, NULL, NULL, NULL, 8, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 80, 65, NULL, NULL, NULL, NULL, 14, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 100, 100, NULL, NULL, NULL, NULL, 22, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 120, 155, NULL, NULL, NULL, NULL, 32, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 140, 230, NULL, NULL, NULL, NULL, 44, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 160, 340, NULL, NULL, NULL, NULL, 58, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 180, 500, NULL, NULL, NULL, NULL, 72, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 200, 720, NULL, NULL, NULL, NULL, 88, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 210, 860, NULL, NULL, NULL, NULL, 96, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 220, 1020, NULL, NULL, NULL, NULL, 104, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 230, 1200, NULL, NULL, NULL, NULL, 113, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 240, 1400, NULL, NULL, NULL, NULL, 122, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 250, 1620, NULL, NULL, NULL, NULL, 131, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 260, 1870, NULL, NULL, NULL, NULL, 140, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 270, 2140, NULL, NULL, NULL, NULL, 150, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 280, 2440, NULL, NULL, NULL, NULL, 160, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 290, 2760, NULL, NULL, NULL, NULL, 170, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 300, 3100, NULL, NULL, NULL, NULL, 180, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 310, 3450, NULL, NULL, NULL, NULL, 190, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 320, 3800, NULL, NULL, NULL, NULL, 199, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 330, 4150, NULL, NULL, NULL, NULL, 208, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 340, 4500, NULL, NULL, NULL, NULL, 216, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 350, 4850, NULL, NULL, NULL, NULL, 224, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 360, 5200, NULL, NULL, NULL, NULL, 231, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 380, 5850, NULL, NULL, NULL, NULL, 244, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 400, 6500, NULL, NULL, NULL, NULL, 255, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 420, 7100, NULL, NULL, NULL, NULL, 264, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 450, 7900, NULL, NULL, NULL, NULL, 276, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 480, 8600, NULL, NULL, NULL, NULL, 285, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 510, 9200, NULL, NULL, NULL, NULL, 292, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Female', 540, 9700, NULL, NULL, NULL, NULL, 297, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 0, 1, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 20, 10, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 40, 23, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 60, 42, NULL, NULL, NULL, NULL, 8, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 80, 70, NULL, NULL, NULL, NULL, 15, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 100, 110, NULL, NULL, NULL, NULL, 23, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 120, 170, NULL, NULL, NULL, NULL, 34, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 140, 260, NULL, NULL, NULL, NULL, 47, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 160, 380, NULL, NULL, NULL, NULL, 62, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 180, 560, NULL, NULL, NULL, NULL, 78, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 200, 800, NULL, NULL, NULL, NULL, 95, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 210, 960, NULL, NULL, NULL, NULL, 104, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 220, 1140, NULL, NULL, NULL, NULL, 113, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 230, 1350, NULL, NULL, NULL, NULL, 122, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 240, 1580, NULL, NULL, NULL, NULL, 132, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 250, 1840, NULL, NULL, NULL, NULL, 142, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 260, 2130, NULL, NULL, NULL, NULL, 152, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 270, 2450, NULL, NULL, NULL, NULL, 163, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 280, 2800, NULL, NULL, NULL, NULL, 174, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 290, 3180, NULL, NULL, NULL, NULL, 185, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 300, 3580, NULL, NULL, NULL, NULL, 196, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 310, 4000, NULL, NULL, NULL, NULL, 207, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 320, 4430, NULL, NULL, NULL, NULL, 217, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 330, 4880, NULL, NULL, NULL, NULL, 227, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 340, 5340, NULL, NULL, NULL, NULL, 236, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 350, 5800, NULL, NULL, NULL, NULL, 245, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 360, 6280, NULL, NULL, NULL, NULL, 253, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 380, 7200, NULL, NULL, NULL, NULL, 268, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 400, 8100, NULL, NULL, NULL, NULL, 281, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 420, 9000, NULL, NULL, NULL, NULL, 292, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 450, 10200, NULL, NULL, NULL, NULL, 306, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 480, 11400, NULL, NULL, NULL, NULL, 317, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 510, 12500, NULL, NULL, NULL, NULL, 326, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Eastern Grey Kangaroo', 'Male', 540, 13500, NULL, NULL, NULL, NULL, 333, NULL, NULL, NULL, 'Poole et al. 1982 / ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 0, 1, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 30, 12, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 60, 30, NULL, NULL, NULL, NULL, 7, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 90, 60, NULL, NULL, NULL, NULL, 16, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 120, 110, NULL, NULL, NULL, NULL, 28, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 150, 200, NULL, NULL, NULL, NULL, 42, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 180, 380, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 200, 550, NULL, NULL, NULL, NULL, 72, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 210, 660, NULL, NULL, NULL, NULL, 79, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 220, 780, NULL, NULL, NULL, NULL, 86, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 230, 920, NULL, NULL, NULL, NULL, 93, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 240, 1080, NULL, NULL, NULL, NULL, 101, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 250, 1260, NULL, NULL, NULL, NULL, 109, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 260, 1460, NULL, NULL, NULL, NULL, 117, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 270, 1670, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 280, 1890, NULL, NULL, NULL, NULL, 133, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 300, 2350, NULL, NULL, NULL, NULL, 148, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 320, 2820, NULL, NULL, NULL, NULL, 162, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 340, 3280, NULL, NULL, NULL, NULL, 174, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 360, 3700, NULL, NULL, NULL, NULL, 184, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 390, 4250, NULL, NULL, NULL, NULL, 196, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 420, 4700, NULL, NULL, NULL, NULL, 205, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Female', 450, 5050, NULL, NULL, NULL, NULL, 212, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 0, 1, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 30, 13, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 60, 32, NULL, NULL, NULL, NULL, 7, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 90, 65, NULL, NULL, NULL, NULL, 17, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 120, 120, NULL, NULL, NULL, NULL, 30, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 150, 220, NULL, NULL, NULL, NULL, 45, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 180, 420, NULL, NULL, NULL, NULL, 64, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 200, 620, NULL, NULL, NULL, NULL, 77, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 210, 740, NULL, NULL, NULL, NULL, 84, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 220, 880, NULL, NULL, NULL, NULL, 92, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 230, 1040, NULL, NULL, NULL, NULL, 100, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 240, 1220, NULL, NULL, NULL, NULL, 108, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 250, 1420, NULL, NULL, NULL, NULL, 117, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 260, 1650, NULL, NULL, NULL, NULL, 126, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 270, 1900, NULL, NULL, NULL, NULL, 135, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 280, 2170, NULL, NULL, NULL, NULL, 144, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 300, 2750, NULL, NULL, NULL, NULL, 162, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 320, 3380, NULL, NULL, NULL, NULL, 179, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 340, 4020, NULL, NULL, NULL, NULL, 194, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 360, 4680, NULL, NULL, NULL, NULL, 208, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 390, 5600, NULL, NULL, NULL, NULL, 225, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 420, 6500, NULL, NULL, NULL, NULL, 239, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 450, 7300, NULL, NULL, NULL, NULL, 250, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common Wallaroo', 'Male', 480, 8000, NULL, NULL, NULL, NULL, 258, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 0, 1, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 30, 8, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 60, 20, NULL, NULL, NULL, NULL, 6, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 80, 35, NULL, NULL, NULL, NULL, 12, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 100, 58, NULL, NULL, NULL, NULL, 20, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 120, 92, NULL, NULL, NULL, NULL, 30, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 140, 145, NULL, NULL, NULL, NULL, 42, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 160, 225, NULL, NULL, NULL, NULL, 56, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 180, 340, NULL, NULL, NULL, NULL, 70, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 200, 500, NULL, NULL, NULL, NULL, 86, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 210, 600, NULL, NULL, NULL, NULL, 94, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 220, 710, NULL, NULL, NULL, NULL, 102, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 230, 830, NULL, NULL, NULL, NULL, 111, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 240, 970, NULL, NULL, NULL, NULL, 120, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 250, 1120, NULL, NULL, NULL, NULL, 129, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 260, 1290, NULL, NULL, NULL, NULL, 138, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 270, 1470, NULL, NULL, NULL, NULL, 147, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 280, 1660, NULL, NULL, NULL, NULL, 155, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 300, 2060, NULL, NULL, NULL, NULL, 171, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 320, 2470, NULL, NULL, NULL, NULL, 185, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 340, 2870, NULL, NULL, NULL, NULL, 197, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 360, 3250, NULL, NULL, NULL, NULL, 207, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 390, 3750, NULL, NULL, NULL, NULL, 219, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 420, 4150, NULL, NULL, NULL, NULL, 228, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Female', 450, 4450, NULL, NULL, NULL, NULL, 234, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 0, 1, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 30, 9, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 60, 22, NULL, NULL, NULL, NULL, 6, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 80, 38, NULL, NULL, NULL, NULL, 13, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 100, 62, NULL, NULL, NULL, NULL, 21, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 120, 100, NULL, NULL, NULL, NULL, 32, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 140, 160, NULL, NULL, NULL, NULL, 45, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 160, 250, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 180, 380, NULL, NULL, NULL, NULL, 76, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 200, 560, NULL, NULL, NULL, NULL, 93, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 210, 670, NULL, NULL, NULL, NULL, 102, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 220, 800, NULL, NULL, NULL, NULL, 111, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 230, 950, NULL, NULL, NULL, NULL, 120, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 240, 1120, NULL, NULL, NULL, NULL, 130, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 250, 1310, NULL, NULL, NULL, NULL, 140, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 260, 1520, NULL, NULL, NULL, NULL, 150, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 270, 1750, NULL, NULL, NULL, NULL, 160, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 280, 2000, NULL, NULL, NULL, NULL, 170, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 300, 2530, NULL, NULL, NULL, NULL, 189, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 320, 3090, NULL, NULL, NULL, NULL, 206, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 340, 3660, NULL, NULL, NULL, NULL, 221, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 360, 4220, NULL, NULL, NULL, NULL, 234, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 390, 5000, NULL, NULL, NULL, NULL, 250, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 420, 5700, NULL, NULL, NULL, NULL, 262, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Red-necked wallaby', 'Male', 450, 6300, NULL, NULL, NULL, NULL, 271, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 0, 1, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 30, 9, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 60, 22, NULL, NULL, NULL, NULL, 6, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 80, 38, NULL, NULL, NULL, NULL, 12, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 100, 62, NULL, NULL, NULL, NULL, 20, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 120, 98, NULL, NULL, NULL, NULL, 30, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 140, 155, NULL, NULL, NULL, NULL, 42, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 160, 240, NULL, NULL, NULL, NULL, 56, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 180, 370, NULL, NULL, NULL, NULL, 71, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 200, 550, NULL, NULL, NULL, NULL, 88, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 210, 660, NULL, NULL, NULL, NULL, 96, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 220, 790, NULL, NULL, NULL, NULL, 105, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 230, 940, NULL, NULL, NULL, NULL, 114, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 240, 1100, NULL, NULL, NULL, NULL, 123, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 250, 1280, NULL, NULL, NULL, NULL, 132, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 260, 1480, NULL, NULL, NULL, NULL, 141, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 270, 1690, NULL, NULL, NULL, NULL, 150, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 280, 1910, NULL, NULL, NULL, NULL, 159, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 300, 2370, NULL, NULL, NULL, NULL, 175, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 320, 2830, NULL, NULL, NULL, NULL, 189, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 340, 3270, NULL, NULL, NULL, NULL, 201, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 360, 3680, NULL, NULL, NULL, NULL, 211, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 390, 4200, NULL, NULL, NULL, NULL, 222, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Female', 420, 4600, NULL, NULL, NULL, NULL, 230, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 0, 1, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 30, 10, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 60, 24, NULL, NULL, NULL, NULL, 7, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 80, 42, NULL, NULL, NULL, NULL, 13, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 100, 68, NULL, NULL, NULL, NULL, 22, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 120, 110, NULL, NULL, NULL, NULL, 33, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 140, 175, NULL, NULL, NULL, NULL, 46, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 160, 275, NULL, NULL, NULL, NULL, 61, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 180, 420, NULL, NULL, NULL, NULL, 78, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 200, 630, NULL, NULL, NULL, NULL, 96, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 210, 760, NULL, NULL, NULL, NULL, 105, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 220, 910, NULL, NULL, NULL, NULL, 115, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 230, 1080, NULL, NULL, NULL, NULL, 125, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 240, 1280, NULL, NULL, NULL, NULL, 135, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 250, 1500, NULL, NULL, NULL, NULL, 145, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 260, 1740, NULL, NULL, NULL, NULL, 156, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 270, 2000, NULL, NULL, NULL, NULL, 167, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 280, 2280, NULL, NULL, NULL, NULL, 177, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 300, 2870, NULL, NULL, NULL, NULL, 197, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 320, 3480, NULL, NULL, NULL, NULL, 215, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 340, 4090, NULL, NULL, NULL, NULL, 230, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 360, 4680, NULL, NULL, NULL, NULL, 243, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 390, 5480, NULL, NULL, NULL, NULL, 258, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 420, 6150, NULL, NULL, NULL, NULL, 269, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Swamp wallaby', 'Male', 450, 6700, NULL, NULL, NULL, NULL, 277, NULL, NULL, NULL, 'ARAZPA'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 0, 0.2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 14, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 28, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 42, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 56, 18, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 70, 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 84, 48, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 98, 72, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 112, 105, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 126, 148, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 140, 200, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 150, 240, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 160, 285, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 170, 340, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 180, 400, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 190, 470, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 200, 545, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 210, 620, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 230, 780, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 250, 940, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 270, 1080, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 300, 1280, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 330, 1450, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Female', 360, 1580, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 0, 0.2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 14, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 28, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 42, 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 56, 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 70, 33, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 84, 52, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 98, 78, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 112, 115, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 126, 160, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 140, 218, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 150, 262, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 160, 312, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 170, 372, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 180, 440, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 190, 520, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 200, 605, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 210, 695, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 230, 880, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 250, 1070, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 270, 1250, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 300, 1520, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 330, 1760, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common brushtail possum', 'Male', 360, 1950, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kerle 1984'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 0, 0.2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 14, 1.5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 28, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 42, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 56, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 70, 22, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 84, 34, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 98, 50, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 112, 72, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 120, 86, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 130, 105, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 140, 128, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 150, 155, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 160, 185, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 170, 220, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 180, 258, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 200, 340, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 220, 420, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 240, 490, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 270, 570, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Female', 300, 630, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 0, 0.2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 14, 1.5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 28, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 42, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 56, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 70, 24, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 84, 37, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 98, 55, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 112, 78, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 120, 94, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 130, 115, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 140, 140, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 150, 170, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 160, 205, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 170, 245, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 180, 290, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 200, 385, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 220, 480, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 240, 565, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 270, 670, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Common Ringtail Possum', 'Male', 300, 740, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'How 1983'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 0, 25, NULL, NULL, 55, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 3, 30, NULL, NULL, 57, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 7, 38, NULL, NULL, 60, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 10, 45, NULL, NULL, 63, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 14, 55, NULL, NULL, 67, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 17, 63, NULL, NULL, 70, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 21, 75, NULL, NULL, 74, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 24, 85, NULL, NULL, 77, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 28, 98, NULL, NULL, 81, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 31, 108, NULL, NULL, 84, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 35, 122, NULL, NULL, 88, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 38, 133, NULL, NULL, 91, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 42, 148, NULL, NULL, 95, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 45, 160, NULL, NULL, 98, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 49, 175, NULL, NULL, 102, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 52, 188, NULL, NULL, 105, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 56, 205, NULL, NULL, 108, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 60, 220, NULL, NULL, 112, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 63, 232, NULL, NULL, 114, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 70, 262, NULL, NULL, 120, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 77, 290, NULL, NULL, 126, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 84, 320, NULL, NULL, 131, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 91, 348, NULL, NULL, 136, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 98, 375, NULL, NULL, 140, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 105, 400, NULL, NULL, 144, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 112, 420, NULL, NULL, 147, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 120, 440, NULL, NULL, 150, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 135, 470, NULL, NULL, 154, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Female', 150, 490, NULL, NULL, 157, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 0, 27, NULL, NULL, 56, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 3, 32, NULL, NULL, 58, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 7, 42, NULL, NULL, 61, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 10, 50, NULL, NULL, 64, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 14, 62, NULL, NULL, 68, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 17, 72, NULL, NULL, 72, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 21, 85, NULL, NULL, 76, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 24, 96, NULL, NULL, 79, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 28, 112, NULL, NULL, 83, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 31, 124, NULL, NULL, 87, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 35, 140, NULL, NULL, 91, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 38, 153, NULL, NULL, 94, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 42, 170, NULL, NULL, 98, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 45, 185, NULL, NULL, 102, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 49, 203, NULL, NULL, 106, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 52, 218, NULL, NULL, 109, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 56, 238, NULL, NULL, 113, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 60, 256, NULL, NULL, 116, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 63, 270, NULL, NULL, 119, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 70, 305, NULL, NULL, 125, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 77, 340, NULL, NULL, 131, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 84, 375, NULL, NULL, 137, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 91, 408, NULL, NULL, 142, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 98, 440, NULL, NULL, 147, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 105, 470, NULL, NULL, 151, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 112, 498, NULL, NULL, 155, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 120, 525, NULL, NULL, 158, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 135, 570, NULL, NULL, 163, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Grey-headed Flying Fox', 'Male', 150, 600, NULL, NULL, 166, NULL, NULL, NULL, NULL, NULL, 'Divljan 2006 / Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 0, 18, NULL, NULL, 42, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 3, 22, NULL, NULL, 44, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 7, 28, NULL, NULL, 47, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 10, 33, NULL, NULL, 49, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 14, 40, NULL, NULL, 52, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 17, 46, NULL, NULL, 55, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 21, 55, NULL, NULL, 58, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 24, 62, NULL, NULL, 61, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 28, 72, NULL, NULL, 65, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 31, 80, NULL, NULL, 68, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 35, 90, NULL, NULL, 71, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 38, 98, NULL, NULL, 74, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 42, 108, NULL, NULL, 77, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 45, 116, NULL, NULL, 80, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 49, 126, NULL, NULL, 83, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 52, 134, NULL, NULL, 85, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 56, 144, NULL, NULL, 88, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 60, 152, NULL, NULL, 91, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 63, 158, NULL, NULL, 93, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 70, 174, NULL, NULL, 97, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 77, 188, NULL, NULL, 101, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 84, 200, NULL, NULL, 104, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 91, 210, NULL, NULL, 107, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 98, 218, NULL, NULL, 110, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 105, 225, NULL, NULL, 112, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Female', 120, 235, NULL, NULL, 116, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 0, 20, NULL, NULL, 43, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 3, 24, NULL, NULL, 45, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 7, 30, NULL, NULL, 48, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 10, 36, NULL, NULL, 50, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 14, 44, NULL, NULL, 54, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 17, 50, NULL, NULL, 57, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 21, 60, NULL, NULL, 60, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 24, 68, NULL, NULL, 63, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 28, 78, NULL, NULL, 67, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 31, 87, NULL, NULL, 70, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 35, 98, NULL, NULL, 74, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 38, 107, NULL, NULL, 76, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 42, 118, NULL, NULL, 80, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 45, 127, NULL, NULL, 83, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 49, 138, NULL, NULL, 86, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 52, 147, NULL, NULL, 89, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 56, 158, NULL, NULL, 92, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 60, 168, NULL, NULL, 94, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 63, 175, NULL, NULL, 96, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 70, 192, NULL, NULL, 101, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 77, 208, NULL, NULL, 105, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 84, 222, NULL, NULL, 109, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 91, 234, NULL, NULL, 112, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 98, 244, NULL, NULL, 115, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 105, 252, NULL, NULL, 117, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000'),
  (gen_random_uuid(), 'Little Red Flying-fox', 'Male', 120, 265, NULL, NULL, 121, NULL, NULL, NULL, NULL, NULL, 'Hall & Richards 2000')
ON CONFLICT (species_name, sex, age_days) DO NOTHING;
