import { formatAbn, formatAmountCents } from '@/lib/receipts';
import type { EofyStatement } from '@/lib/eofy';

// Server-rendered, print-styled consolidated annual donation statement. Members
// and admins save it as PDF via the browser print dialog (same approach as the
// per-payment receipt). The tax-deductible claim line only appears when the org
// is an endorsed DGR.
export function EofyStatementView({ data }: { data: EofyStatement }) {
  const { org, donorName, donorEmail, fyLabel, lines, totalCents, currency, taxDeductible } = data;

  return (
    <div className="receipt mx-auto max-w-2xl bg-white text-black p-10 print:p-0">
      <style>{`
        @media print {
          @page { margin: 1.5cm; }
          body { background: white; }
          .no-print { display: none !important; }
        }
        .receipt h1 { font-size: 1.5rem; font-weight: 700; }
        .receipt h2 { font-size: 1.1rem; font-weight: 600; margin-top: 1.5rem; }
        .receipt table { width: 100%; border-collapse: collapse; }
        .receipt table th, .receipt table td { padding: 0.5rem 0; border-bottom: 1px solid #e5e7eb; text-align: left; }
        .receipt table td.num, .receipt table th.num { text-align: right; font-variant-numeric: tabular-nums; }
        .receipt .label { color: #6b7280; font-size: 0.85rem; }
      `}</style>

      <header className="border-b pb-4 mb-6">
        <h1>{org.name}</h1>
        <p className="text-sm text-gray-600 mt-1">
          {org.abn ? `ABN ${formatAbn(org.abn)}` : 'ABN not on file'}
          {org.dgrEndorsed ? ' · Endorsed Deductible Gift Recipient' : ''}
        </p>
        {(org.contactEmail || org.contactPhone) && (
          <p className="text-sm text-gray-600 mt-1">
            {[org.contactEmail, org.contactPhone].filter(Boolean).join(' · ')}
          </p>
        )}
      </header>

      <h1 className="!text-xl">Annual donation statement</h1>
      <p className="text-sm text-gray-600 mt-1">Financial year {fyLabel}</p>

      <div className="grid grid-cols-2 gap-4 my-6">
        <div className="col-span-2">
          <div className="label">Issued to</div>
          <div>{donorName ?? '—'}</div>
          <div className="text-sm text-gray-600">{donorEmail}</div>
        </div>
      </div>

      <h2>Donations received</h2>
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Receipt</th>
            <th className="num">Amount</th>
          </tr>
        </thead>
        <tbody>
          {lines.map((l, i) => (
            <tr key={i}>
              <td>
                {l.date.toLocaleDateString('en-AU', {
                  day: '2-digit',
                  month: 'short',
                  year: 'numeric',
                  timeZone: 'Australia/Sydney',
                })}
              </td>
              <td className="font-mono">{l.receiptNumber ?? '—'}</td>
              <td className="num font-mono">{formatAmountCents(l.amountCents, currency)}</td>
            </tr>
          ))}
          <tr>
            <th>
              Total ({lines.length} {lines.length === 1 ? 'donation' : 'donations'})
            </th>
            <td></td>
            <td className="num font-mono font-bold">{formatAmountCents(totalCents, currency)}</td>
          </tr>
        </tbody>
      </table>

      <h2>Tax notice</h2>
      {taxDeductible ? (
        <p className="text-sm">
          The donations listed above are gifts of money of $2 or more to a Deductible Gift Recipient
          endorsed under Subdivision 30-B of the Income Tax Assessment Act 1997. Total
          tax-deductible amount for the year:{' '}
          <strong>{formatAmountCents(totalCents, currency)}</strong>. Please retain this statement
          for your taxation records.
        </p>
      ) : (
        <p className="text-sm">
          This organisation is not endorsed as a Deductible Gift Recipient, so the donations listed
          above are <strong>not</strong> tax deductible. Retain this statement for your records.
        </p>
      )}

      <footer className="mt-10 pt-4 border-t text-xs text-gray-500">
        Generated by WildTrack360 · This is an automatically generated statement and is valid
        without signature.
      </footer>
    </div>
  );
}
