import {
  formatAmountCents,
  receiptKindLabel,
  type ReceiptData,
} from '@/lib/receipts';

// Server-rendered, print-styled HTML receipt. Members + admins can save as
// PDF via the browser's print dialog (no native PDF dep needed). Branches the
// copy on PaymentKind + OrganisationSettings.dgrEndorsed so the tax-deductible
// claim line only appears when both conditions hold.
export function ReceiptView({ data }: { data: ReceiptData }) {
  const { payment, org, donorEmail, donorName, taxDeductible } = data;
  const issuedAt = new Date(payment.createdAt);

  return (
    <div className="receipt mx-auto max-w-2xl bg-white text-black p-10 print:p-0">
      <style>{`
        @media print {
          @page { margin: 1.5cm; }
          body { background: white; }
          .no-print { display: none !important; }
        }
        .receipt h1 { font-size: 1.5rem; font-weight: 700; }
        .receipt h2 { font-size: 1.1rem; font-weight: 600; margin-top: 1.5rem; }
        .receipt table { width: 100%; border-collapse: collapse; }
        .receipt table th, .receipt table td { padding: 0.5rem 0; border-bottom: 1px solid #e5e7eb; text-align: left; }
        .receipt .label { color: #6b7280; font-size: 0.85rem; }
      `}</style>

      <header className="border-b pb-4 mb-6">
        <h1>{org.name}</h1>
        <p className="text-sm text-gray-600 mt-1">
          {org.abn ? `ABN ${org.abn}` : 'ABN not on file'}
          {org.dgrEndorsed ? ' · Endorsed Deductible Gift Recipient' : ''}
        </p>
        {(org.contactEmail || org.contactPhone) && (
          <p className="text-sm text-gray-600 mt-1">
            {[org.contactEmail, org.contactPhone].filter(Boolean).join(' · ')}
          </p>
        )}
      </header>

      <div className="grid grid-cols-2 gap-4 mb-6">
        <div>
          <div className="label">Receipt number</div>
          <div className="font-mono">{payment.receiptNumber ?? '—'}</div>
        </div>
        <div>
          <div className="label">Date issued</div>
          <div>{issuedAt.toLocaleDateString('en-AU', { day: '2-digit', month: 'long', year: 'numeric' })}</div>
        </div>
        <div className="col-span-2">
          <div className="label">Issued to</div>
          <div>{donorName ?? '—'}</div>
          <div className="text-sm text-gray-600">{donorEmail}</div>
        </div>
      </div>

      <h2>Payment details</h2>
      <table>
        <tbody>
          <tr>
            <th>Description</th>
            <td>{receiptKindLabel(payment.kind)}</td>
          </tr>
          <tr>
            <th>Amount paid</th>
            <td className="font-mono">{formatAmountCents(payment.amountCents, payment.currency)}</td>
          </tr>
          <tr>
            <th>Currency</th>
            <td>{payment.currency}</td>
          </tr>
          <tr>
            <th>Status</th>
            <td>{payment.status}</td>
          </tr>
        </tbody>
      </table>

      <h2>Tax notice</h2>
      {taxDeductible ? (
        <p className="text-sm">
          This receipt is for a gift of money of $2 or more to a Deductible Gift
          Recipient endorsed under Subdivision 30-B of the Income Tax Assessment
          Act 1997. Tax-deductible portion: <strong>{formatAmountCents(payment.amountCents, payment.currency)}</strong>.
        </p>
      ) : payment.kind.startsWith('MEMBERSHIP') ? (
        <p className="text-sm">
          Membership fees are <strong>not</strong> tax deductible. Retain this
          receipt for your records.
        </p>
      ) : (
        <p className="text-sm">
          This organisation is not endorsed as a Deductible Gift Recipient.
          Donations made here are <strong>not</strong> tax deductible.
        </p>
      )}

      <footer className="mt-10 pt-4 border-t text-xs text-gray-500">
        Generated by WildTrack360 · This is an automatically generated receipt and is valid without signature.
      </footer>
    </div>
  );
}
