export interface SpeciesData {
  name: string;
  scientificName: string;
  speciesCode?: string;
  category: 'Basic' | 'Exempt' | 'Unprotected';
  type: 'Mammal' | 'Amphibian' | 'Reptile' | 'Bird';
  subtype?: string;
}

export const speciesSeedData: SpeciesData[] = [
  // Mammals
  { name: 'Fat-tailed dunnart', scientificName: 'Sminthopsis crassicaudata', speciesCode: 'A01072', category: 'Basic', type: 'Mammal', subtype: 'Dunnart' },
  { name: 'Wild dog', scientificName: 'Canis familiaris', category: 'Unprotected', type: 'Mammal', subtype: 'Dingo' },
  { name: 'Squirrel glider', scientificName: 'Petaurus norfolcensis', speciesCode: 'E04226', category: 'Basic', type: 'Mammal', subtype: 'Gliders' },
  { name: 'Sugar glider', scientificName: 'Petaurus breviceps', speciesCode: 'E01138', category: 'Basic', type: 'Mammal', subtype: 'Gliders' },
  { name: 'Common brushtail possum', scientificName: 'Trichosurus vulpecula', speciesCode: 'K01113', category: 'Basic', type: 'Mammal', subtype: 'Possum' },
  { name: 'Brush-tailed bettong (Woylie)', scientificName: 'Bettongia penicillata ogilbyi', speciesCode: 'M21002', category: 'Basic', type: 'Mammal', subtype: 'Potoroo and bettongs' },
  { name: 'Long-nosed potoroo', scientificName: 'Potorous tridactylus', speciesCode: 'Z01175', category: 'Basic', type: 'Mammal', subtype: 'Potoroo and bettongs' },
  { name: 'Rufous bettong', scientificName: 'Aepyprymnus rufescens', speciesCode: 'W01187', category: 'Basic', type: 'Mammal', subtype: 'Potoroo and bettongs' },
  { name: "Mitchell's hopping-mouse", scientificName: 'Notomys mitchellii', speciesCode: 'Y01480', category: 'Basic', type: 'Mammal', subtype: 'Rodents' },
  { name: 'Plains mouse (Rat)', scientificName: 'Pseudomys australis', speciesCode: 'S01469', category: 'Basic', type: 'Mammal', subtype: 'Rodents' },
  { name: 'Spinifex hopping-mouse', scientificName: 'Notomys alexis', speciesCode: 'K01481', category: 'Exempt', type: 'Mammal', subtype: 'Rodents' },
  { name: 'Parma wallaby', scientificName: 'Macropus parma', speciesCode: 'K01245', category: 'Basic', type: 'Mammal', subtype: 'Wallabies' },
  { name: 'Red-necked pademelon', scientificName: 'Thylogale thetis', speciesCode: 'Y01236', category: 'Basic', type: 'Mammal', subtype: 'Wallabies' },
  { name: 'Red-necked wallaby', scientificName: 'Macropus rufogriseus', speciesCode: 'K01261', category: 'Basic', type: 'Mammal', subtype: 'Wallabies' },
  { name: 'Swamp wallaby', scientificName: 'Wallabia bicolor', speciesCode: 'E01242', category: 'Basic', type: 'Mammal', subtype: 'Wallabies' },
  { name: 'Tammar wallaby', scientificName: 'Macropus eugenii eugenii', speciesCode: 'C05889', category: 'Basic', type: 'Mammal', subtype: 'Wallabies' },
  { name: 'Tasmanian pademelon', scientificName: 'Thylogale billardierii', speciesCode: 'G01235', category: 'Basic', type: 'Mammal', subtype: 'Wallabies' },

  // Mammals - Wombats
  { name: 'Common wombat', scientificName: 'Vombatus ursinus', category: 'Basic', type: 'Mammal', subtype: 'Wombats' },
  { name: 'Northern hairy-nosed wombat', scientificName: 'Lasiorhinus krefftii', category: 'Basic', type: 'Mammal', subtype: 'Wombats' },
  { name: 'Southern hairy-nosed wombat', scientificName: 'Lasiorhinus latifrons', category: 'Basic', type: 'Mammal', subtype: 'Wombats' },

  // Amphibians
  { name: 'Southern bell frog', scientificName: 'Litoria raniformis', speciesCode: 'G03207', category: 'Basic', type: 'Amphibian' },
  { name: 'Smooth frog', scientificName: 'Geocrinia laevis', speciesCode: 'C03029', category: 'Basic', type: 'Amphibian' },

  // Reptiles - Dragon lizards
  { name: 'Black-collared dragon', scientificName: 'Ctenophorus clayi', speciesCode: 'Z02179', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Central bearded dragon', scientificName: 'Pogona vitticeps', speciesCode: 'Y02204', category: 'Exempt', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Central netted dragon', scientificName: 'Ctenophorus nuchalis', speciesCode: 'Q02196', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Crested dragon', scientificName: 'Ctenophorus cristatus', speciesCode: 'A02180', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Downs bearded dragon', scientificName: 'Pogona henrylawsoni', speciesCode: 'U05586', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Dwarf bearded dragon', scientificName: 'Pogona minor minor', speciesCode: 'G21035', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Eastern bearded dragon', scientificName: 'Pogona barbata', speciesCode: 'K02177', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Eyrean earless dragon', scientificName: 'Tympanocryptis tetraporophora', speciesCode: 'K02257', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Eyre Peninsula dragon', scientificName: 'Ctenophorus fionni', speciesCode: 'Y02184', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: "Gilbert's dragon", scientificName: 'Lophognathus gilberti', speciesCode: 'E02246', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Jacky lizard', scientificName: 'Amphibolurus muricatus', speciesCode: 'M02194', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Kimberley bearded dragon', scientificName: 'Pogona microlepidota', speciesCode: 'W05587', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Lined earless dragon', scientificName: 'Tympanocryptis lineata', speciesCode: 'G02255', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Long-nosed dragon', scientificName: 'Gowidon longirostris', speciesCode: 'G02247', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Mallee dragon', scientificName: 'Ctenophorus fordi', speciesCode: 'K02185', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Military dragon', scientificName: 'Ctenophorus isolepis', speciesCode: 'Z02187', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Mountain dragon', scientificName: 'Rankinia diemensis', speciesCode: 'E02182', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Nobbi dragon', scientificName: 'Diporiphora nobbi', speciesCode: 'Z02195', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'North-west bearded dragon', scientificName: 'Pogona minor mitchelli', speciesCode: 'C04313', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Ornate dragon', scientificName: 'Ctenophorus ornatus', speciesCode: 'U02198', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Painted dragon', scientificName: 'Ctenophorus pictus', speciesCode: 'W02199', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Red-barred dragon', scientificName: 'Ctenophorus vadnappa', speciesCode: 'G02203', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Ring-tailed dragon', scientificName: 'Ctenophorus caudicinctus', speciesCode: 'M02178', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Southern angle-headed dragon', scientificName: 'Lophosaurus spinipes', speciesCode: 'C02245', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Tawny dragon', scientificName: 'Ctenophorus decresii', speciesCode: 'C02181', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Water dragon', scientificName: 'Intellagama lesueurii', speciesCode: 'A02252', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Western bearded dragon', scientificName: 'Pogona minor minima', speciesCode: 'G02191', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },
  { name: 'Western netted dragon', scientificName: 'Ctenophorus reticulatus', speciesCode: 'A02200', category: 'Basic', type: 'Reptile', subtype: 'Dragon lizards' },

  // Reptiles - Geckos
  { name: 'Banded knob-tail', scientificName: 'Nephrurus wheeleri', speciesCode: 'M05590', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Banded velvet gecko', scientificName: 'Oedura cincta', speciesCode: 'Z02119', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Beaded gecko', scientificName: 'Lucasium damaeum', speciesCode: 'K02109', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: "Bynoe's gecko", scientificName: 'Heteronotia binoei', speciesCode: 'C02105', category: 'Exempt', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Centralian knob-tailed gecko', scientificName: 'Nephrurus amyae', speciesCode: 'A04312', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Common barking gecko', scientificName: 'Underwoodisaurus milii', speciesCode: 'U02138', category: 'Exempt', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Common knob-tailed gecko', scientificName: 'Nephrurus levis', speciesCode: 'A02112', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Dotted velvet gecko', scientificName: 'Oedura gemmata', speciesCode: 'C05589', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Eastern stone gecko', scientificName: 'Diplodactylus vittatus (revised)', speciesCode: 'Q04492', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Fringe-toed velvet gecko', scientificName: 'Oedura filicipoda', speciesCode: 'A05588', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Gibber gecko', scientificName: 'Lucasium byrnei', speciesCode: 'Y02052', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Golden-tailed gecko', scientificName: 'Strophurus taenicauda', speciesCode: 'W02075', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Helmeted gecko', scientificName: 'Diplodactylus galeatus', speciesCode: 'S02057', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Jewelled gecko', scientificName: 'Strophurus elderi', speciesCode: 'Z02055', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: "Lesueur's velvet gecko", scientificName: 'Amalosia lesueurii', speciesCode: 'M02118', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Map gecko', scientificName: 'Lucasium steindachneri', speciesCode: 'K04261', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Marbled gecko', scientificName: 'Christinus marmoratus', speciesCode: 'M02126', category: 'Exempt', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Northern giant cave gecko', scientificName: 'Pseudothecadactylus lindneri', speciesCode: 'Z02135', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Northern knob-tailed gecko', scientificName: 'Nephrurus sheai', speciesCode: 'Z05583', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Northern spiny-tailed gecko', scientificName: 'Strophurus ciliaris', speciesCode: 'K02053', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Northern spotted velvet gecko', scientificName: 'Oedura coggeri', speciesCode: 'K02117', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Northern velvet gecko', scientificName: 'Oedura castelnaui', speciesCode: 'Y02116', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Ocellated velvet gecko', scientificName: 'Oedura monilis', speciesCode: 'A02120', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Pale knob-tailed gecko', scientificName: 'Nephrurus laevissimus', speciesCode: 'W02111', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Phasmid striped gecko', scientificName: 'Strophurus taeniatus', speciesCode: 'A05596', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Ring-tailed gecko', scientificName: 'Cyrtodactylus tuberculatus', speciesCode: 'S02049', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Robust tree dtella', scientificName: 'Gehyra purpurascens', speciesCode: 'K02089', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Robust velvet gecko', scientificName: 'Nebulifera robusta', speciesCode: 'G02123', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Rough knob-tail', scientificName: 'Nephrurus asper', speciesCode: 'U02110', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Rough-throated leaf-tailed gecko', scientificName: 'Saltuarius salebrosus', speciesCode: 'C05597', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Sandplain gecko', scientificName: 'Lucasium stenodactylum', speciesCode: 'Q04424', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Short-tailed dtella', scientificName: 'Gehyra baliola', speciesCode: 'G05599', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Southern spiny-tailed gecko', scientificName: 'Strophurus intermedius', speciesCode: 'W02059', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Southern spotted velvet gecko', scientificName: 'Oedura tryoni', speciesCode: 'Y02124', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Starred knob-tailed gecko', scientificName: 'Nephrurus stellatus', speciesCode: 'C02113', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Western spiny-tailed gecko', scientificName: 'Strophurus strophurus', speciesCode: 'Y05600', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Wheat-belt stone gecko', scientificName: 'Diplodactylus granariensis (revised)', speciesCode: 'U05622', category: 'Basic', type: 'Reptile', subtype: 'Geckos' },
  { name: 'Western tree dtella', scientificName: 'Gehyra variegata', speciesCode: 'Z05371', category: 'Exempt', type: 'Reptile', subtype: 'Geckos' },

  // Reptiles - Legless lizards
  { name: 'Common scaly-foot', scientificName: 'Pygopus lepidopodus', speciesCode: 'E02174', category: 'Basic', type: 'Reptile', subtype: 'Legless lizards' },
  { name: 'Eastern hooded scaly-foot', scientificName: 'Pygopus schraderi', speciesCode: 'Q04044', category: 'Basic', type: 'Reptile', subtype: 'Legless lizards' },
  { name: 'Excitable delma', scientificName: 'Delma tincta', speciesCode: 'C02165', category: 'Basic', type: 'Reptile', subtype: 'Legless lizards' },
  { name: 'Gulfs delma', scientificName: 'Delma molleri', speciesCode: 'S02161', category: 'Basic', type: 'Reptile', subtype: 'Legless lizards' },
  { name: 'Patternless delma', scientificName: 'Delma inornata', speciesCode: 'Q02160', category: 'Basic', type: 'Reptile', subtype: 'Legless lizards' },
  { name: 'Western hooded scaly-foot', scientificName: 'Pygopus nigriceps', speciesCode: 'G02175', category: 'Basic', type: 'Reptile', subtype: 'Legless lizards' },

  // Reptiles - Monitors and goannas
  { name: 'Black-headed monitor', scientificName: 'Varanus tristis', speciesCode: 'M02282', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Black-palmed monitor', scientificName: 'Varanus glebopalma', speciesCode: 'K05601', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Black-spotted spiny-tailed monitor', scientificName: 'Varanus baritji', speciesCode: 'G04315', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Desert pygmy goanna', scientificName: 'Varanus eremius', speciesCode: 'M02266', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: "Gould's goanna", scientificName: 'Varanus gouldii gouldii', speciesCode: 'U21022', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Kimberley rock monitor', scientificName: 'Varanus glauerti', speciesCode: 'S02269', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Long-tailed rock monitor', scientificName: 'Varanus kingorum', speciesCode: 'M05602', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Mangrove monitor', scientificName: 'Varanus indicus', speciesCode: 'Y02272', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: "Mertens' water monitor", scientificName: 'Varanus mertensi', speciesCode: 'K02273', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: "Mitchell's water monitor", scientificName: 'Varanus mitchelli', speciesCode: 'M02274', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Northern ridge-tailed monitor', scientificName: 'Varanus primordius', speciesCode: 'Z05603', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Pilbara Mulga monitor', scientificName: 'Varanus bushi', speciesCode: 'K05581', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Pilbara rock monitor', scientificName: 'Varanus pilbarensis', speciesCode: 'Q05604', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Pygmy Mulga goanna', scientificName: 'Varanus gilleni', speciesCode: 'Q02268', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Ridge-tailed monitor', scientificName: 'Varanus acanthurus', speciesCode: 'G02263', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Rusty monitor', scientificName: 'Varanus semiremex', speciesCode: 'U02278', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Sand monitor (arid subspecies)', scientificName: 'Varanus gouldii flavirufus', speciesCode: 'W21023', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Short-tailed pygmy goanna', scientificName: 'Varanus brevicauda', speciesCode: 'Y04112', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: "Spencer's monitor", scientificName: 'Varanus spenceri', speciesCode: 'W02279', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Spotted tree monitor', scientificName: 'Varanus scalaris', speciesCode: 'K05493', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: "Storr's monitor", scientificName: 'Varanus storri', speciesCode: 'S05605', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },
  { name: 'Stripe-tailed monitor', scientificName: 'Varanus caudolineatus', speciesCode: 'U05606', category: 'Basic', type: 'Reptile', subtype: 'Monitors and goannas' },

  // Reptiles - Skinks
  { name: 'Adelaide snake-eye', scientificName: 'Morethia adelaidensis', speciesCode: 'S02525', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Black rock skink', scientificName: 'Egernia saxatilis', speciesCode: 'K02425', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Blacksoil skink', scientificName: 'Proablepharus kinghorni', speciesCode: 'Q04192', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Blotched bluetongue', scientificName: 'Tiliqua nigrolutea', speciesCode: 'U02578', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: "Bougainville's skink", scientificName: 'Lerista bougainvillii', speciesCode: 'G02475', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Broad-banded sandswimmer', scientificName: 'Eremiascincus richardsonii', speciesCode: 'U02438', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Bull skink', scientificName: 'Liopholis multiscutata', speciesCode: 'A02420', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Centralian bluetongue', scientificName: 'Tiliqua multifasciata', speciesCode: 'S02577', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Centralian Ranges rock-skink', scientificName: 'Liopholis margaretae', speciesCode: 'M02418', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Common desert ctenotus', scientificName: 'Ctenotus leonhardii', speciesCode: 'S02365', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Common snake-eye', scientificName: 'Morethia boulengeri', speciesCode: 'U02526', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Copper-tailed skink', scientificName: 'Ctenotus taeniolatus', speciesCode: 'E02386', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: "Cunningham's skink", scientificName: 'Egernia cunninghami', speciesCode: 'Y02408', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Dampier Land limbless slider', scientificName: 'Lerista apoda', speciesCode: 'Q05620', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Dark barsided skink', scientificName: 'Concinnia martini', speciesCode: 'W04507', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Delicate skink', scientificName: 'Lampropholis delicata', speciesCode: 'M02450', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Desert skink', scientificName: 'Liopholis inornata', speciesCode: 'C02413', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Dwarf skink', scientificName: 'Menetia greyii', speciesCode: 'W02519', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Eastern bluetongue', scientificName: 'Tiliqua scincoides', speciesCode: 'Y02580', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Eastern crevice skink', scientificName: 'Egernia mcpheei', speciesCode: 'S04505', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Eastern desert ctenotus', scientificName: 'Ctenotus regius', speciesCode: 'U02374', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Eastern striped skink', scientificName: 'Ctenotus spaldingi', speciesCode: 'W02375', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Eastern three-lined skink', scientificName: 'Acritoscincus duperreyi', speciesCode: 'U02682', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Eastern tree skink', scientificName: 'Egernia striolata', speciesCode: 'S02429', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Eastern water skink', scientificName: 'Eulamprus quoyii', speciesCode: 'K02557', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Four-toed earless skink', scientificName: 'Hemiergis peronii', speciesCode: 'U02446', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Garden skink', scientificName: 'Lampropholis guichenoti', speciesCode: 'Z02451', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Gidgee skink', scientificName: 'Egernia stokesii', speciesCode: 'Z02427', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Goldfields crevice-skink', scientificName: 'Egernia formosa', speciesCode: 'M05610', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: "Hosmer's skink", scientificName: 'Egernia hosmeri', speciesCode: 'A02412', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: "King's skink", scientificName: 'Egernia kingii', speciesCode: 'E02414', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Land mullet', scientificName: 'Bellatorias major', speciesCode: 'K02417', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Lined soil-crevice skink', scientificName: 'Notoscincus butleri', speciesCode: 'Z05611', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Mainland she-oak skink', scientificName: 'Cyclodomorphus michaeli', speciesCode: 'U04506', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Major skink', scientificName: 'Bellatorias frerei', speciesCode: 'W02411', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Mallee snake-eye', scientificName: 'Morethia obscura', speciesCode: 'C02529', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: "Murray's skink", scientificName: 'Silvascincus murrayi', speciesCode: 'Q05612', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Myall slider', scientificName: 'Lerista edwardsae', speciesCode: 'G04023', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Narrow-banded sandswimmer', scientificName: 'Eremiascincus fasciolatus (revised)', speciesCode: 'S05621', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Night skink', scientificName: 'Liopholis striata', speciesCode: 'Q02428', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Northern bar-lipped skink', scientificName: 'Eremiascincus isolepis', speciesCode: 'S05613', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Pink-tongued lizard', scientificName: 'Cyclodomorphus gerrardii', speciesCode: 'Y05492', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Pin-striped ctenotus', scientificName: 'Ctenotus ariadnae', speciesCode: 'Z02339', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Pygmy spiny-tailed skink', scientificName: 'Egernia depressa', speciesCode: 'K02409', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Robust rainbow-skink', scientificName: 'Carlia schmeltzii', speciesCode: 'U05614', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Sandhill ctenotus', scientificName: 'Ctenotus brooksi', speciesCode: 'G02343', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Sandplain ctenotus', scientificName: 'Ctenotus schomburgkii', speciesCode: 'G02379', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Sleepy lizard', scientificName: 'Tiliqua rugosa', speciesCode: 'Z02583', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Southern four-toed slider', scientificName: 'Lerista dorsalis', speciesCode: 'E02482', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Southern robust slider', scientificName: 'Lerista picturata', speciesCode: 'Q02496', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Southern three-toed slider', scientificName: 'Lerista terdigitata', speciesCode: 'E02502', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Southern water skink', scientificName: 'Eulamprus tympanum', speciesCode: 'C02561', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Speckled wall skink', scientificName: 'Cryptoblepharus pannosus', speciesCode: 'Q04328', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Spotted slider', scientificName: 'Lerista punctatovittata', speciesCode: 'W02499', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Striped wall skink', scientificName: 'Cryptoblepharus pulcher', speciesCode: 'W02331', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Taper-tailed west-coast slider', scientificName: 'Lerista humphriesi', speciesCode: 'E05618', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Three-toed earless skink', scientificName: 'Hemiergis decresiensis', speciesCode: 'K02441', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Three-toed skink', scientificName: 'Saiphos equalis', speciesCode: 'G05619', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Western bluetongue', scientificName: 'Tiliqua occipitalis', speciesCode: 'W02579', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: 'Western earless skink', scientificName: 'Hemiergis initialis', speciesCode: 'Z02443', category: 'Basic', type: 'Reptile', subtype: 'Skinks' },
  { name: "White's skink", scientificName: 'Liopholis whitii', speciesCode: 'E02430', category: 'Exempt', type: 'Reptile', subtype: 'Skinks' },

  // Reptiles - Snakes
  { name: 'Black-headed python', scientificName: 'Aspidites melanocephalus', speciesCode: 'Q02612', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: 'Brown tree snake', scientificName: 'Boiga irregularis', speciesCode: 'U02630', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: 'Carpet python', scientificName: 'Morelia spilota', speciesCode: 'C02625', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: 'Centralian carpet python', scientificName: 'Morelia bredli', speciesCode: 'W05607', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: 'Childrens python', scientificName: 'Antaresia childreni', speciesCode: 'M05582', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: 'Common (green) tree snake', scientificName: 'Dendrelaphis punctulatus', speciesCode: 'C02633', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: 'Keelback snake', scientificName: 'Tropidonophis mairii', speciesCode: 'K02629', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: 'Northern tree snake', scientificName: 'Dendrelaphis calligastra', speciesCode: 'A02632', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: 'Olive python', scientificName: 'Liasis olivaceus', speciesCode: 'S02621', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: 'Rough-scaled python', scientificName: 'Morelia carinata', speciesCode: 'A05608', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: 'Slaty-grey snake', scientificName: 'Stegonotus cucullatus', speciesCode: 'M02638', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: 'Spotted python', scientificName: 'Antaresia maculosa', speciesCode: 'C05609', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: "Stimson's python", scientificName: 'Antaresia stimsoni', speciesCode: 'G02619', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: 'Water python', scientificName: 'Liasis fuscus', speciesCode: 'Q02620', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },
  { name: 'Woma', scientificName: 'Aspidites ramsayi', speciesCode: 'S02613', category: 'Basic', type: 'Reptile', subtype: 'Snakes' },

  // Reptiles - Turtles and tortoises
  { name: 'Broadshelled tortoise', scientificName: 'Chelodina expansa', speciesCode: 'A02016', category: 'Basic', type: 'Reptile', subtype: 'Turtles and tortoises' },
  { name: 'Eastern long-necked tortoise', scientificName: 'Chelodina longicollis', speciesCode: 'C02017', category: 'Exempt', type: 'Reptile', subtype: 'Turtles and tortoises' },
  { name: 'Jardine River turtle', scientificName: 'Emydura subglobosa', speciesCode: 'S05585', category: 'Basic', type: 'Reptile', subtype: 'Turtles and tortoises' },
  { name: "Krefft's River turtle", scientificName: 'Emydura macquarii krefftii', speciesCode: 'C02033', category: 'Basic', type: 'Reptile', subtype: 'Turtles and tortoises' },
  { name: 'Macquarie River turtle', scientificName: 'Emydura macquarii macquarii', speciesCode: 'W05579', category: 'Exempt', type: 'Reptile', subtype: 'Turtles and tortoises' },
  { name: 'Northern snake-necked turtle', scientificName: 'Chelodina oblonga', speciesCode: 'Q02020', category: 'Basic', type: 'Reptile', subtype: 'Turtles and tortoises' },
  { name: 'Northern snapping turtle', scientificName: 'Elseya dentata', speciesCode: 'Y02028', category: 'Basic', type: 'Reptile', subtype: 'Turtles and tortoises' },
  { name: 'Northern yellow-faced turtle', scientificName: 'Emydura tanybaraga', speciesCode: 'Q05584', category: 'Basic', type: 'Reptile', subtype: 'Turtles and tortoises' },
  { name: 'North-west red-faced turtle', scientificName: 'Emydura victoriae', speciesCode: 'Y05580', category: 'Basic', type: 'Reptile', subtype: 'Turtles and tortoises' },
  { name: 'Oblong turtle', scientificName: 'Chelodina colliei', speciesCode: 'G02019', category: 'Basic', type: 'Reptile', subtype: 'Turtles and tortoises' },
  { name: 'Saw-shelled turtle', scientificName: 'Wollumbinia latisternum', speciesCode: 'K02029', category: 'Basic', type: 'Reptile', subtype: 'Turtles and tortoises' },

  // Birds - Cockatoos and parrots
  { name: 'Adelaide rosellas', scientificName: 'Platycercus elegans (fleurieuensis & subadelaidae)', speciesCode: 'G00283', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Australian king-parrot', scientificName: 'Alisterus scapularis', speciesCode: 'C00281', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Blue-cheeked rosella', scientificName: 'Platycercus adscitus adscitus', speciesCode: 'A21024', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Blue-winged parrot', scientificName: 'Neophema chrysostoma', speciesCode: 'M00306', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: "Bourke's parrot", scientificName: 'Neopsephotus bourkii', speciesCode: 'Y00304', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Budgerygah', scientificName: 'Melopsittacus undulatus', category: 'Unprotected', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Cloncurry', scientificName: 'Barnardius zonarius macgillivrayi', speciesCode: 'W21031', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Cockatiel', scientificName: 'Nymphicus hollandicus', speciesCode: 'E00274', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Crimson rosella', scientificName: 'Platycercus elegans (elegans & melanopterus)', speciesCode: 'A15072', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Eastern rosella', scientificName: 'Platycercus eximius', speciesCode: 'S04177', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Eclectus parrot', scientificName: 'Eclectus roratus macgillivrayi', speciesCode: 'C21033', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Elegant parrot', scientificName: 'Neophema elegans', speciesCode: 'Z00307', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Galah', scientificName: 'Cacatua roseicapilla', category: 'Unprotected', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Golden-shouldered parrot', scientificName: 'Psephotus chrysopterygius', speciesCode: 'A00300', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Green rosella', scientificName: 'Platycercus caledonicus', speciesCode: 'K00285', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Hooded parrot', scientificName: 'Psephotus dissimilis', speciesCode: 'C00301', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Kimberley northern rosella', scientificName: 'Platycercus venustus hilli', speciesCode: 'Q05488', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Little corella', scientificName: 'Cacatua sanguinea', category: 'Unprotected', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Little lorikeet', scientificName: 'Parvipsitta pusilla', speciesCode: 'Q00260', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Long-billed corella', scientificName: 'Cacatua tenuirostris', speciesCode: 'A00272', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: "Major Mitchell's cockatoo", scientificName: 'Lophochroa leadbeateri', speciesCode: 'U00270', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Mallee ringneck', scientificName: 'Barnardius zonarius barnardi', speciesCode: 'U21030', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Mulga parrot', scientificName: 'Psephotellus varius', speciesCode: 'Q00296', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Musk lorikeet', scientificName: 'Glossopsitta concinna', speciesCode: 'E00258', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: "Northern rosella (Brown's rosella)", scientificName: 'Platycercus venustus', speciesCode: 'Z00287', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Pale-headed rosella', scientificName: 'Platycercus adscitus', speciesCode: 'M00286', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Port Lincoln parrot', scientificName: 'Barnardius zonarius zonarius', speciesCode: 'S05489', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Princess parrot', scientificName: 'Polytelis alexandrae', speciesCode: 'Z00279', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Purple-crowned lorikeet', scientificName: 'Parvipsitta porphyrocephala', speciesCode: 'G00259', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Rainbow lorikeet', scientificName: 'Trichoglossus haematodus', speciesCode: 'U00254', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Red-capped parrot', scientificName: 'Purpureicephalus spurius', speciesCode: 'E00290', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Red-collared lorikeet', scientificName: 'Trichoglossus haematodus rubritorquis', speciesCode: 'W00255', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Red-rumped parrot', scientificName: 'Psephotus haematonotus', speciesCode: 'Z00295', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Red-vented blue bonnet', scientificName: 'Northiella haematogaster haematorrhous', speciesCode: 'M08002', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Red-winged parrot', scientificName: 'Aprosmictus erythropterus', speciesCode: 'M04246', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Regent parrot (eastern subspecies)', scientificName: 'Polytelis anthopeplus monarchoides', speciesCode: 'C04381', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Regent parrot (WA subspecies)', scientificName: 'Polytelis anthopeplus anthopeplus', speciesCode: 'E05490', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Rock parrot', scientificName: 'Neophema petrophila', speciesCode: 'Q00308', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Scaly-breasted lorikeet', scientificName: 'Trichoglossus chlorolepidotus', speciesCode: 'A00256', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Scarlet-chested parrot', scientificName: 'Neophema splendida', speciesCode: 'G00303', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Sulphur-crested cockatoo', scientificName: 'Cacatua galerita', speciesCode: 'Q04176', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Superb parrot', scientificName: 'Polytelis swainsonii', speciesCode: 'K00277', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Turquoise parrot', scientificName: 'Neophema pulchella', speciesCode: 'E00302', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Twenty-eight parrot', scientificName: 'Barnardius zonarius semitorquatus', speciesCode: 'K00293', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Varied lorikeet', scientificName: 'Psitteuteles versicolor', speciesCode: 'C00257', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Western corella', scientificName: 'Cacatua pastinator', speciesCode: 'G05503', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Western rosella', scientificName: 'Platycercus icterotis', speciesCode: 'S00289', category: 'Exempt', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Yellow rosella', scientificName: 'Platycercus elegans flaveolus', speciesCode: 'Y00284', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },
  { name: 'Yellow-vented blue bonnet', scientificName: 'Northiella haematogaster haematogaster', speciesCode: 'A21032', category: 'Basic', type: 'Bird', subtype: 'Cockatoos and parrots' },

  // Birds - Crows
  { name: 'Australian crow', scientificName: 'Corvus orru cecilae', category: 'Unprotected', type: 'Bird', subtype: 'Crows' },
  { name: 'Australian raven', scientificName: 'Corvus coronoides', category: 'Unprotected', type: 'Bird', subtype: 'Crows' },
  { name: 'Little crow', scientificName: 'Corvus bennetti', category: 'Unprotected', type: 'Bird', subtype: 'Crows' },
  { name: 'Little raven', scientificName: 'Corvus mellori', category: 'Unprotected', type: 'Bird', subtype: 'Crows' },

  // Birds - Cuckooshrike
  { name: 'Black-faced cuckooshrike', scientificName: 'Coracina novaehollandiae', speciesCode: 'Y04120', category: 'Basic', type: 'Bird', subtype: 'Cuckooshrike' },

  // Birds - Ducks, geese and swans
  { name: 'Australasian shoveler (Blue-winged)', scientificName: 'Anas rhynchotis', speciesCode: 'M04182', category: 'Basic', type: 'Bird', subtype: 'Ducks, geese and swans' },
  { name: 'Australian shelduck', scientificName: 'Tadorna tadornoides', speciesCode: 'G00207', category: 'Basic', type: 'Bird', subtype: 'Ducks, geese and swans' },
  { name: 'Black swan', scientificName: 'Cygnus atratus', speciesCode: 'W00203', category: 'Basic', type: 'Bird', subtype: 'Ducks, geese and swans' },
  { name: 'Cape Barren goose', scientificName: 'Cereopsis novaehollandiae novaehollandiae', speciesCode: 'M00198', category: 'Basic', type: 'Bird', subtype: 'Ducks, geese and swans' },
  { name: 'Chestnut teal', scientificName: 'Anas castanea', speciesCode: 'U00210', category: 'Exempt', type: 'Bird', subtype: 'Ducks, geese and swans' },
  { name: 'Grey teal (Australasian teal)', scientificName: 'Anas gracilis', speciesCode: 'Y04148', category: 'Basic', type: 'Bird', subtype: 'Ducks, geese and swans' },
  { name: 'Hardhead (White-eyed duck)', scientificName: 'Aythya australis', speciesCode: 'G00215', category: 'Basic', type: 'Bird', subtype: 'Ducks, geese and swans' },
  { name: 'Magpie goose', scientificName: 'Anseranas semipalmata', speciesCode: 'Z00199', category: 'Basic', type: 'Bird', subtype: 'Ducks, geese and swans' },
  { name: 'Maned duck (Australian wood duck)', scientificName: 'Chenonetta jubata', speciesCode: 'U00202', category: 'Exempt', type: 'Bird', subtype: 'Ducks, geese and swans' },
  { name: 'Pacific black duck', scientificName: 'Anas superciliosa', speciesCode: 'E04146', category: 'Exempt', type: 'Bird', subtype: 'Ducks, geese and swans' },
  { name: 'Plumed whistling duck', scientificName: 'Dendrocygna eytoni', speciesCode: 'C00205', category: 'Exempt', type: 'Bird', subtype: 'Ducks, geese and swans' },
  { name: 'Raja shelduck', scientificName: 'Tadorna radjah', speciesCode: 'E00206', category: 'Basic', type: 'Bird', subtype: 'Ducks, geese and swans' },
  { name: 'Wandering whistling duck', scientificName: 'Dendrocygna arcuata', speciesCode: 'A00204', category: 'Basic', type: 'Bird', subtype: 'Ducks, geese and swans' },

  // Birds - Dotterel and stilt
  { name: 'Inland dotterel', scientificName: 'Peltohyas australis', speciesCode: 'K00145', category: 'Basic', type: 'Bird', subtype: 'Dotterel and stilt' },
  { name: 'White-headed (black-winged) stilt', scientificName: 'Himantopus leucocephalus', speciesCode: 'M00146', category: 'Basic', type: 'Bird', subtype: 'Dotterel and stilt' },

  // Birds - Emu
  { name: 'Emu', scientificName: 'Dromaius novaehollandiae', speciesCode: 'C00001', category: 'Basic', type: 'Bird', subtype: 'Emu' },

  // Birds - Fairywrens
  { name: 'Black-backed fairywren', scientificName: 'Malurus splendens melanotis', speciesCode: 'E00530', category: 'Basic', type: 'Bird', subtype: 'Fairywrens' },
  { name: 'Red-backed fairywren', scientificName: 'Malurus melanocephalus', speciesCode: 'K00541', category: 'Basic', type: 'Bird', subtype: 'Fairywrens' },
  { name: 'Splendid fairywren', scientificName: 'Malurus splendens splendens', speciesCode: 'E21034', category: 'Basic', type: 'Bird', subtype: 'Fairywrens' },
  { name: 'Superb fairywren', scientificName: 'Malurus cyaneus', speciesCode: 'S00529', category: 'Basic', type: 'Bird', subtype: 'Fairywrens' },
  { name: 'Turquoise fairywren', scientificName: 'Malurus splendens callainus', speciesCode: 'G05491', category: 'Basic', type: 'Bird', subtype: 'Fairywrens' },
  { name: 'Variegated fairywren', scientificName: 'Malurus lamberti', speciesCode: 'Q00536', category: 'Basic', type: 'Bird', subtype: 'Fairywrens' },
  { name: 'White-winged fairywren', scientificName: 'Malurus leucopterus', speciesCode: 'Z00535', category: 'Basic', type: 'Bird', subtype: 'Fairywrens' },

  // Birds - Frogmouth
  { name: 'Tawny frogmouth', scientificName: 'Podargus strigoides', speciesCode: 'K00313', category: 'Basic', type: 'Bird', subtype: 'Frogmouth' },

  // Birds - Finches
  { name: 'Black-throated finch (Diggles)', scientificName: 'Poephila cincta atropygialis', speciesCode: 'Y05504', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Black-throated finch (Parson)', scientificName: 'Poephila cincta cincta', speciesCode: 'C21025', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Chestnut-breasted mannikin', scientificName: 'Lonchura castaneothorax', speciesCode: 'K00657', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Crimson finch (Common)', scientificName: 'Neochmia phaeton phaeton', speciesCode: 'E21018', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Crimson finch (white-bellied subspecies)', scientificName: 'Neochmia phaeton evangelinae', speciesCode: 'G21019', category: 'Basic', type: 'Bird', subtype: 'Finches' },
  { name: 'Diamond Firetail', scientificName: 'Stagonopleura guttata', speciesCode: 'A00652', category: 'Basic', type: 'Bird', subtype: 'Finches' },
  { name: 'Double-barred finch (Black rump)', scientificName: 'Stizoptera bichenovii annulosa', speciesCode: 'G21027', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Double-barred finch (White rump)', scientificName: 'Stizoptera bichenovii bichenovii', speciesCode: 'Y21028', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Gouldian finch', scientificName: 'Erythrura gouldiae', speciesCode: 'E00670', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Long-tailed finch (Hecks)', scientificName: 'Poephila acuticauda hecki', speciesCode: 'K05505', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Long-tailed finch (Longtail)', scientificName: 'Poephila acuticauda acuticauda', speciesCode: 'E21026', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Masked finch (Masked)', scientificName: 'Poephila personata personata', speciesCode: 'A21016', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Masked finch (White-eared)', scientificName: 'Poephila personata leucotis', speciesCode: 'C21017', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Painted finch', scientificName: 'Emblema pictum', speciesCode: 'E00654', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Pictorella mannikin', scientificName: 'Heteromunia pectoralis', speciesCode: 'Z00659', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Plum-headed finch', scientificName: 'Neochmia modesta', speciesCode: 'Q04512', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Red-browed finch', scientificName: 'Neochmia temporalis', speciesCode: 'G04075', category: 'Basic', type: 'Bird', subtype: 'Finches' },
  { name: 'Red-eared firetail', scientificName: 'Stagonopleura oculata', speciesCode: 'W00651', category: 'Basic', type: 'Bird', subtype: 'Finches' },
  { name: 'Star finch', scientificName: 'Neochmia ruficauda', speciesCode: 'G00663', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Yellow-rumped mannikin', scientificName: 'Lonchura flaviprymna', speciesCode: 'M00658', category: 'Exempt', type: 'Bird', subtype: 'Finches' },
  { name: 'Zebra finch', scientificName: 'Poephila guttata', category: 'Unprotected', type: 'Bird', subtype: 'Finches' },

  // Birds - Honeyeaters and chats
  { name: 'Blue-faced honeyeater', scientificName: 'Entomyzon cyanotis', speciesCode: 'Y04200', category: 'Basic', type: 'Bird', subtype: 'Honeyeaters and chats' },
  { name: 'Crescent honeyeater', scientificName: 'Phylidonyris pyrrhopterus', speciesCode: 'M00630', category: 'Basic', type: 'Bird', subtype: 'Honeyeaters and chats' },
  { name: 'Crimson chat', scientificName: 'Epthianura tricolor', speciesCode: 'S00449', category: 'Basic', type: 'Bird', subtype: 'Honeyeaters and chats' },
  { name: 'Little wattlebird', scientificName: 'Anthochaera chrysoptera', speciesCode: 'G04163', category: 'Exempt', type: 'Bird', subtype: 'Honeyeaters and chats' },
  { name: 'New Holland honeyeater', scientificName: 'Phylidonyris novaehollandiae', speciesCode: 'U04126', category: 'Exempt', type: 'Bird', subtype: 'Honeyeaters and chats' },
  { name: 'Noisy miner', scientificName: 'Manorina melanocephala', speciesCode: 'U00634', category: 'Exempt', type: 'Bird', subtype: 'Honeyeaters and chats' },
  { name: 'Orange chat', scientificName: 'Epthianura aurifrons', speciesCode: 'E00450', category: 'Basic', type: 'Bird', subtype: 'Honeyeaters and chats' },
  { name: 'Pied honeyeater', scientificName: 'Certhionyx variegatus', speciesCode: 'E00602', category: 'Basic', type: 'Bird', subtype: 'Honeyeaters and chats' },
  { name: 'Red wattlebird', scientificName: 'Anthochaera carunculata', category: 'Unprotected', type: 'Bird', subtype: 'Honeyeaters and chats' },
  { name: 'Scarlet honeyeater', scientificName: 'Myzomela sanguinolenta', speciesCode: 'M00586', category: 'Basic', type: 'Bird', subtype: 'Honeyeaters and chats' },
  { name: 'White-fronted chat', scientificName: 'Epthianura albifrons', speciesCode: 'Z04131', category: 'Basic', type: 'Bird', subtype: 'Honeyeaters and chats' },
  { name: 'White-fronted honeyeater', scientificName: 'Purnella albifrons', speciesCode: 'M00594', category: 'Basic', type: 'Bird', subtype: 'Honeyeaters and chats' },
  { name: 'White-plumed honeyeater', scientificName: 'Ptilotula penicillata', speciesCode: 'S00625', category: 'Exempt', type: 'Bird', subtype: 'Honeyeaters and chats' },

  // Birds - Kookaburras
  { name: 'Blue-winged kookaburra', scientificName: 'Dacelo leachii', speciesCode: 'Z00323', category: 'Basic', type: 'Bird', subtype: 'Kookaburras' },
  { name: 'Laughing kookaburra', scientificName: 'Dacelo novaeguineae', speciesCode: 'S04169', category: 'Basic', type: 'Bird', subtype: 'Kookaburras' },

  // Birds - Magpie
  { name: 'Australian Magpie', scientificName: 'Gymnorhina tibicen', speciesCode: 'S00705', category: 'Exempt', type: 'Bird', subtype: 'Magpie' },

  // Birds - Magpielark
  { name: 'Magpielark', scientificName: 'Grallina cyanoleuca', speciesCode: 'W00415', category: 'Exempt', type: 'Bird', subtype: 'Magpielark' },

  // Birds - Nativehens
  { name: 'Black-tailed nativehen', scientificName: 'Tribonyx ventralis', speciesCode: 'G00055', category: 'Basic', type: 'Bird', subtype: 'Nativehens' },
  { name: 'Dusky moorhen', scientificName: 'Gallinula tenebrosa', speciesCode: 'C04145', category: 'Basic', type: 'Bird', subtype: 'Nativehens' },
  { name: 'Tasmanian nativehen', scientificName: 'Tribonyx mortierii', speciesCode: 'E04250', category: 'Basic', type: 'Bird', subtype: 'Nativehens' },

  // Birds - Owl
  { name: 'Southern boobook', scientificName: 'Ninox boobook', speciesCode: 'M00242', category: 'Basic', type: 'Bird', subtype: 'Owl' },

  // Birds - Pigeons and doves
  { name: 'Bar-shouldered dove', scientificName: 'Geopelia humeralis', speciesCode: 'Q00032', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Brown cuckoo-dove', scientificName: 'Macropygia amboinensis', speciesCode: 'C00029', category: 'Basic', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Brush bronzewing', scientificName: 'Phaps elegans', speciesCode: 'U04142', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Common bronzewing', scientificName: 'Phaps chalcoptera', speciesCode: 'U00034', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Crested pigeon', scientificName: 'Ocyphaps lophotes', speciesCode: 'W00043', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Diamond dove', scientificName: 'Geopelia cuneata', speciesCode: 'Z00031', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Emerald dove', scientificName: 'Chalcophaps indica', speciesCode: 'S00033', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Flock bronzewing', scientificName: 'Phaps histrionica', speciesCode: 'A00036', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Partridge pigeon', scientificName: 'Geophaps smithii', speciesCode: 'Q00040', category: 'Basic', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Peaceful dove', scientificName: 'Geopelia placida', speciesCode: 'Q04168', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Rose-crowned fruit-dove', scientificName: 'Ptilinopus regina', speciesCode: 'K00021', category: 'Basic', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Spinifex pigeon', scientificName: 'Geophaps plumifera', speciesCode: 'U00042', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Spinifex pigeon (red fronted)', scientificName: 'Geophaps plumifera ferruginea', speciesCode: 'K21029', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Squatter pigeon', scientificName: 'Geophaps scripta', speciesCode: 'G00039', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Superb fruit-dove', scientificName: 'Ptilinopus superbus', speciesCode: 'Z00023', category: 'Basic', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Torresian imperial-pigeon', scientificName: 'Ducula bicolor spilorrhoa', speciesCode: 'U00026', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'White-headed pigeon', scientificName: 'Columba leucomela', speciesCode: 'A00028', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },
  { name: 'Wonga pigeon', scientificName: 'Leucosarcia melanoleuca', speciesCode: 'A00044', category: 'Exempt', type: 'Bird', subtype: 'Pigeons and doves' },

  // Birds - Plovers and gulls
  { name: 'Banded lapwing', scientificName: 'Vanellus tricolor', speciesCode: 'G00135', category: 'Basic', type: 'Bird', subtype: 'Plovers and gulls' },
  { name: 'Masked lapwing (northern subspecies)', scientificName: 'Vanellus miles miles', speciesCode: 'C00133', category: 'Basic', type: 'Bird', subtype: 'Plovers and gulls' },
  { name: 'Silver gull', scientificName: 'Chroicocephalus novaehollandiae', speciesCode: 'C04065', category: 'Exempt', type: 'Bird', subtype: 'Plovers and gulls' },
  { name: 'Spur-winged plover', scientificName: 'Vanellus miles novaehollandiae', speciesCode: 'W09343', category: 'Basic', type: 'Bird', subtype: 'Plovers and gulls' },

  // Birds - Quails
  { name: 'Black-breasted buttonquail', scientificName: 'Turnix melanogaster', speciesCode: 'S00017', category: 'Exempt', type: 'Bird', subtype: 'Quails' },
  { name: 'Brown quail (Swamp partridge)', scientificName: 'Coturnix ypsilophora ypsilophora', speciesCode: 'W21015', category: 'Exempt', type: 'Bird', subtype: 'Quails' },
  { name: 'Brown quail (Swamp quail)', scientificName: 'Coturnix ypsilophora australis', speciesCode: 'Y09304', category: 'Exempt', type: 'Bird', subtype: 'Quails' },
  { name: 'King quail', scientificName: 'Excalfactoria chinensis', speciesCode: 'Y00012', category: 'Exempt', type: 'Bird', subtype: 'Quails' },
  { name: 'Little buttonquail', scientificName: 'Turnix velox', speciesCode: 'U00018', category: 'Exempt', type: 'Bird', subtype: 'Quails' },
  { name: 'Painted buttonquail', scientificName: 'Turnix varius', speciesCode: 'U04178', category: 'Exempt', type: 'Bird', subtype: 'Quails' },
  { name: 'Red-backed buttonquail', scientificName: 'Turnix maculosus', speciesCode: 'K00013', category: 'Basic', type: 'Bird', subtype: 'Quails' },
  { name: 'Red-chested buttonquail', scientificName: 'Turnix pyrrhothorax', speciesCode: 'W00019', category: 'Basic', type: 'Bird', subtype: 'Quails' },
  { name: 'Stubble quail', scientificName: 'Coturnix pectoralis', speciesCode: 'A04240', category: 'Exempt', type: 'Bird', subtype: 'Quails' },

  // Birds - Robins
  { name: 'Eastern yellow robin', scientificName: 'Eopsaltria australis', speciesCode: 'Q00392', category: 'Basic', type: 'Bird', subtype: 'Robins' },
  { name: 'Hooded robin', scientificName: 'Melanodryas cucullata', speciesCode: 'S00385', category: 'Basic', type: 'Bird', subtype: 'Robins' },
  { name: 'Red-capped robin', scientificName: 'Petroica goodenovii', speciesCode: 'K00381', category: 'Basic', type: 'Bird', subtype: 'Robins' },

  // Birds - Stonecurlew
  { name: 'Bush stonecurlew', scientificName: 'Burhinus grallarius', speciesCode: 'U00174', category: 'Basic', type: 'Bird', subtype: 'Stonecurlew' },

  // Birds - White-eye
  { name: 'Grey-backed silvereye', scientificName: 'Zosterops lateralis halmaturina', category: 'Unprotected', type: 'Bird', subtype: 'White-eye' },

  // Birds - Woodswallows
  { name: 'Dusky woodswallow', scientificName: 'Artamus cyanopterus', speciesCode: 'W00547', category: 'Basic', type: 'Bird', subtype: 'Woodswallows' },
  { name: 'Masked woodswallow', scientificName: 'Artamus personatus', speciesCode: 'Q00544', category: 'Basic', type: 'Bird', subtype: 'Woodswallows' },
  { name: 'White-breasted woodswallow', scientificName: 'Artamus leucorhynchus', speciesCode: 'Z00543', category: 'Basic', type: 'Bird', subtype: 'Woodswallows' },
  { name: 'White-browed woodswallow', scientificName: 'Artamus superciliosus', speciesCode: 'S00545', category: 'Basic', type: 'Bird', subtype: 'Woodswallows' }
];