// One-off generator. Reads the NSW DCCEEW Detailed Report XLSX and writes
// the authoritative picklist and species data into src/lib/.
//
// Generates:
//   src/lib/nsw-suburbs.ts       — 4,566 suburb/postcode pairs
//   src/lib/nsw-picklists.ts     — sex, life stage, pouch condition,
//                                  animal condition, encounter type, fate
//   src/lib/nsw-species-list.ts  — ~1,668 species (class/order/family/code)
//
// Run with: npx tsx scripts/extract-nsw-reference-data.ts
//
// When NSW publishes a new financial-year template, drop the new file into
// vendor/ (keeping the same filename or updating SOURCE_XLSX below) and
// re-run this script.

import ExcelJS from 'exceljs';
import { promises as fs } from 'fs';
import path from 'path';

const SOURCE_XLSX = path.join(
  __dirname,
  '..',
  'vendor',
  'wildlife-rehabilitation-detailed-report-2025-26.xlsx',
);
const TARGET_DIR = path.join(__dirname, '..', 'src', 'lib');
const SOURCE_FILENAME = 'wildlife-rehabilitation-detailed-report-2025-26.xlsx';

// ─── Extraction helpers ─────────────────────────────────────────────────────

interface SuburbRow {
  suburb: string;
  postcode: string;
}

interface PicklistItem {
  value: string;
  definition?: string;
  example?: string;
}

interface SpeciesRow {
  class: string;
  order: string;
  familyScientific: string;
  familyCommon: string;
  speciesCode: string;
  scientificName: string;
  commonName: string;
  otherCommonNames: string;
}

function cellText(value: unknown): string {
  if (value == null) return '';
  if (typeof value === 'string') return value.trim();
  if (typeof value === 'number') return String(value);
  if (typeof value === 'object' && value !== null) {
    // ExcelJS rich-text cells have a `richText` array of runs. Other
    // structured values (hyperlinks, formulas) fall back to a safe string.
    const rt = (value as { richText?: { text: string }[] }).richText;
    if (rt) return rt.map((r) => r.text).join('').trim();
    const text = (value as { text?: string }).text;
    if (typeof text === 'string') return text.trim();
    const result = (value as { result?: unknown }).result;
    if (typeof result === 'string' || typeof result === 'number') return String(result).trim();
  }
  return String(value).trim();
}

async function readSheet(wb: ExcelJS.Workbook, name: string): Promise<ExcelJS.Worksheet> {
  const ws = wb.getWorksheet(name);
  if (!ws) throw new Error(`Expected "${name}" sheet not found`);
  return ws;
}

async function extractSuburbs(wb: ExcelJS.Workbook): Promise<SuburbRow[]> {
  const ws = await readSheet(wb, 'Reference Data');
  const out: SuburbRow[] = [];
  for (let r = 2; r <= ws.rowCount; r++) {
    const suburb = cellText(ws.getRow(r).getCell(7).value); // G
    const postcode = cellText(ws.getRow(r).getCell(8).value); // H
    if (!suburb || !postcode) continue;
    out.push({ suburb, postcode });
  }
  return out;
}

function extractSingleColumn(ws: ExcelJS.Worksheet, col: number, startRow: number, endRow: number): string[] {
  const out: string[] = [];
  for (let r = startRow; r <= endRow; r++) {
    const value = cellText(ws.getRow(r).getCell(col).value);
    if (value) out.push(value);
  }
  return out;
}

function extractPicklistWithDefinitions(
  ws: ExcelJS.Worksheet,
  startRow: number,
  endRow: number,
): PicklistItem[] {
  const out: PicklistItem[] = [];
  for (let r = startRow; r <= endRow; r++) {
    const row = ws.getRow(r);
    const value = cellText(row.getCell(1).value);
    if (!value) continue;
    const definition = cellText(row.getCell(2).value) || undefined;
    const example = cellText(row.getCell(3).value) || undefined;
    out.push({ value, definition, example });
  }
  return out;
}

async function extractSpecies(wb: ExcelJS.Workbook): Promise<SpeciesRow[]> {
  const ws = await readSheet(wb, 'Species List');
  const out: SpeciesRow[] = [];
  for (let r = 2; r <= ws.rowCount; r++) {
    const row = ws.getRow(r);
    const commonName = cellText(row.getCell(7).value); // G
    if (!commonName) continue;
    out.push({
      class: cellText(row.getCell(1).value),
      order: cellText(row.getCell(2).value),
      familyScientific: cellText(row.getCell(3).value),
      familyCommon: cellText(row.getCell(4).value),
      speciesCode: cellText(row.getCell(5).value),
      scientificName: cellText(row.getCell(6).value),
      commonName,
      otherCommonNames: cellText(row.getCell(8).value),
    });
  }
  return out;
}

// ─── File formatters ────────────────────────────────────────────────────────

const AUTOGEN_HEADER = `// AUTO-GENERATED by scripts/extract-nsw-reference-data.ts
// Source: vendor/${SOURCE_FILENAME}
// Do not edit by hand. Re-run the extractor when NSW publishes a new template.
`;

function formatSuburbs(suburbs: SuburbRow[]): string {
  return `${AUTOGEN_HEADER}//
// The NSW DCCEEW Detailed Report requires encounter and release locations
// to be selected from an official suburb/postcode drop-down. This module is
// the reference used at intake and on export to validate and canonicalise
// those pairs.

export interface NswSuburbRecord {
  suburb: string;
  postcode: string;
}

export const NSW_SUBURB_POSTCODES: NswSuburbRecord[] = [
${suburbs
  .map(
    (s) => `  { suburb: ${JSON.stringify(s.suburb)}, postcode: ${JSON.stringify(s.postcode)} },`,
  )
  .join('\n')}
];

function normalise(value: string | null | undefined): string {
  return (value ?? '').trim().toLowerCase();
}

// Lookup index for case-insensitive matching. Value is the NSW canonical
// uppercase form ("AARONS PASS - 2850") so callers can emit the exact
// picklist value on export.
const CANONICAL: Map<string, string> = new Map(
  NSW_SUBURB_POSTCODES.map((r) => [
    \`\${normalise(r.suburb)}|\${normalise(r.postcode)}\`,
    \`\${r.suburb} - \${r.postcode}\`,
  ]),
);

export function isKnownNswSuburbPostcode(
  suburb: string | null | undefined,
  postcode: string | null | undefined,
): boolean {
  const s = normalise(suburb);
  const p = normalise(postcode);
  if (!s || !p) return false;
  return CANONICAL.has(\`\${s}|\${p}\`);
}

// Returns NSW's canonical "SUBURB - POSTCODE" picklist form when the pair is
// recognised, or null otherwise. Use this on export to emit the exact value
// NSW's drop-down expects.
export function canonicaliseNswLocation(
  suburb: string | null | undefined,
  postcode: string | null | undefined,
): string | null {
  const s = normalise(suburb);
  const p = normalise(postcode);
  if (!s || !p) return null;
  return CANONICAL.get(\`\${s}|\${p}\`) ?? null;
}

export interface NswLocationValidation {
  valid: boolean;
  // Human-readable explanation suitable for inline UI. Empty when valid.
  warning: string;
}

export function validateNswLocation(input: {
  suburb?: string | null;
  postcode?: string | null;
  state?: string | null;
}): NswLocationValidation {
  const s = normalise(input.suburb);
  const p = normalise(input.postcode);
  const state = normalise(input.state);

  if (!s && !p) {
    return { valid: false, warning: 'Suburb and postcode are required for NSW reporting.' };
  }
  if (!s) return { valid: false, warning: 'Suburb is missing.' };
  if (!p) return { valid: false, warning: 'Postcode is missing.' };

  if (state && state !== 'nsw' && state !== 'new south wales') {
    return {
      valid: false,
      warning: \`State "\${input.state}" is not NSW — this record may need to be excluded from the NSW annual report.\`,
    };
  }
  if (!isKnownNswSuburbPostcode(s, p)) {
    return {
      valid: false,
      warning:
        \`"\${input.suburb} \${input.postcode}" is not in the NSW suburb/postcode picklist. \` +
        'Check spelling or use the closest matching locality from the official list.',
    };
  }
  return { valid: true, warning: '' };
}
`;
}

function formatPicklists(input: {
  sex: string[];
  lifeStage: string[];
  pouch: string[];
  animalCondition: PicklistItem[];
  encounterType: PicklistItem[];
  fate: PicklistItem[];
}): string {
  const renderStringList = (name: string, values: string[]): string =>
    `export const ${name}: readonly string[] = ${JSON.stringify(values, null, 2)} as const;\n`;

  const renderPicklistList = (name: string, items: PicklistItem[]): string => {
    const body = items
      .map((i) => {
        const parts = [`value: ${JSON.stringify(i.value)}`];
        if (i.definition) parts.push(`definition: ${JSON.stringify(i.definition)}`);
        if (i.example) parts.push(`example: ${JSON.stringify(i.example)}`);
        return `  { ${parts.join(', ')} },`;
      })
      .join('\n');
    return `export const ${name}: NswPicklistItem[] = [\n${body}\n];\n`;
  };

  return `${AUTOGEN_HEADER}//
// NSW DCCEEW controlled vocabularies used on the Detailed Report's Datasheet
// tab. Values match the official drop-down text exactly so they can be
// emitted into exports without translation.

export interface NswPicklistItem {
  value: string;
  definition?: string;
  example?: string;
}

${renderStringList('NSW_SEX', input.sex)}
${renderStringList('NSW_LIFE_STAGE', input.lifeStage)}
${renderStringList('NSW_POUCH_CONDITION', input.pouch)}
${renderPicklistList('NSW_ANIMAL_CONDITION', input.animalCondition)}
${renderPicklistList('NSW_ENCOUNTER_TYPE', input.encounterType)}
${renderPicklistList('NSW_FATE', input.fate)}
function normalise(value: string | null | undefined): string {
  return (value ?? '').trim().toLowerCase();
}

function isInPicklist(list: readonly string[] | readonly NswPicklistItem[], value: string | null | undefined): boolean {
  const n = normalise(value);
  if (!n) return false;
  return list.some((item: string | NswPicklistItem) => {
    const v = typeof item === 'string' ? item : item.value;
    return normalise(v) === n;
  });
}

export const isKnownNswSex = (v: string | null | undefined) => isInPicklist(NSW_SEX, v);
export const isKnownNswLifeStage = (v: string | null | undefined) => isInPicklist(NSW_LIFE_STAGE, v);
export const isKnownNswPouchCondition = (v: string | null | undefined) => isInPicklist(NSW_POUCH_CONDITION, v);
export const isKnownNswAnimalCondition = (v: string | null | undefined) => isInPicklist(NSW_ANIMAL_CONDITION, v);
export const isKnownNswEncounterType = (v: string | null | undefined) => isInPicklist(NSW_ENCOUNTER_TYPE, v);
export const isKnownNswFate = (v: string | null | undefined) => isInPicklist(NSW_FATE, v);
`;
}

function formatSpecies(species: SpeciesRow[]): string {
  const body = species
    .map(
      (s) =>
        `  { class: ${JSON.stringify(s.class)}, order: ${JSON.stringify(s.order)}, familyScientific: ${JSON.stringify(s.familyScientific)}, familyCommon: ${JSON.stringify(s.familyCommon)}, speciesCode: ${JSON.stringify(s.speciesCode)}, scientificName: ${JSON.stringify(s.scientificName)}, commonName: ${JSON.stringify(s.commonName)}, otherCommonNames: ${JSON.stringify(s.otherCommonNames)} },`,
    )
    .join('\n');

  return `${AUTOGEN_HEADER}//
// Authoritative NSW species list from the Detailed Report's "Species List"
// tab. Use this to validate the species chosen at intake against the NSW
// DCCEEW picklist. Fall back to the SPECIES_NOT_LISTED sentinel when the
// species is not present.

export interface NswSpeciesRecord {
  class: string;
  order: string;
  familyScientific: string;
  familyCommon: string;
  speciesCode: string;
  scientificName: string;
  commonName: string;
  otherCommonNames: string;
}

export const NSW_SPECIES: NswSpeciesRecord[] = [
${body}
];

function normalise(value: string | null | undefined): string {
  return (value ?? '').trim().toLowerCase();
}

const BY_COMMON_NAME: Map<string, NswSpeciesRecord> = new Map(
  NSW_SPECIES.map((s) => [normalise(s.commonName), s]),
);

export function isKnownNswSpecies(commonName: string | null | undefined): boolean {
  const n = normalise(commonName);
  if (!n) return false;
  return BY_COMMON_NAME.has(n);
}

export function findNswSpeciesByCommonName(
  commonName: string | null | undefined,
): NswSpeciesRecord | null {
  const n = normalise(commonName);
  if (!n) return null;
  return BY_COMMON_NAME.get(n) ?? null;
}
`;
}

// ─── Orchestration ──────────────────────────────────────────────────────────

async function main() {
  console.log(`Reading ${SOURCE_XLSX}`);
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.readFile(SOURCE_XLSX);

  const suburbs = await extractSuburbs(wb);
  console.log(`Suburbs: ${suburbs.length} pairs`);

  const refData = await readSheet(wb, 'Reference Data');
  const sex = extractSingleColumn(refData, 1, 2, 5);
  const lifeStage = extractSingleColumn(refData, 3, 2, 5);
  const pouch = extractSingleColumn(refData, 5, 2, 7);
  console.log(`Sex: ${sex.length}, Life stage: ${lifeStage.length}, Pouch: ${pouch.length}`);

  const animalConditionSheet = await readSheet(wb, 'Animal Condition');
  const animalCondition = extractPicklistWithDefinitions(
    animalConditionSheet,
    3,
    animalConditionSheet.rowCount,
  );
  console.log(`Animal condition: ${animalCondition.length}`);

  const encounterSheet = await readSheet(wb, 'Encounter Type');
  const encounterType = extractPicklistWithDefinitions(encounterSheet, 3, encounterSheet.rowCount);
  console.log(`Encounter type: ${encounterType.length}`);

  const fateSheet = await readSheet(wb, 'Fate');
  const fate = extractPicklistWithDefinitions(fateSheet, 3, fateSheet.rowCount);
  console.log(`Fate: ${fate.length}`);

  const species = await extractSpecies(wb);
  console.log(`Species: ${species.length}`);

  await fs.writeFile(path.join(TARGET_DIR, 'nsw-suburbs.ts'), formatSuburbs(suburbs));
  console.log('Wrote src/lib/nsw-suburbs.ts');

  await fs.writeFile(
    path.join(TARGET_DIR, 'nsw-picklists.ts'),
    formatPicklists({ sex, lifeStage, pouch, animalCondition, encounterType, fate }),
  );
  console.log('Wrote src/lib/nsw-picklists.ts');

  await fs.writeFile(path.join(TARGET_DIR, 'nsw-species-list.ts'), formatSpecies(species));
  console.log('Wrote src/lib/nsw-species-list.ts');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
